### ISSUE TITLE
怎么更换主题色

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-mini#1004]
## 背景
 
我需要的主题色跟默认的不一样，我想可以自己定义主题，组件可以统一替换成我定义的主题色。

**Comment by DiamondYuan** [comment]
可以参考这篇文档 https://ant-design-mini.antgroup.com/guide/customize-theme

**Comment by fangqibin** [comment]
我按照这个文档调整，怎么没有生效，可以给个示例代码吗

**Comment by DiamondYuan** [comment]
> 我按照这个文档调整，怎么没有生效，可以给个示例代码吗

https://github.com/DiamondYuan/ant-design-mini-reproduce/tree/main/less

可以用小程序开发工具打开这个项目。

![image](https://github.com/ant-design/ant-design-mini/assets/9692408/d19565d1-b5b3-45a2-847f-b5af10fd5aa7)

**Comment by fangqibin** [comment]
> > 我按照这个文档调整，怎么没有生效，可以给个示例代码吗
> 
> https://github.com/DiamondYuan/ant-design-mini-reproduce/tree/main/less
> 
> 可以用小程序开发工具打开这个项目。
> 
> ![image](https://private-user-images.githubusercontent.com/9692408/292947726-d19565d1-b5b3-45a2-847f-b5af10fd5aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzA1NDIsIm5iZiI6MTcwMzczMDI0MiwicGF0aCI6Ii85NjkyNDA4LzI5Mjk0NzcyNi1kMTk1NjVkMS1iNWIzLTQ1YTItODQ3Zi1iNWFmMTBmZDVhYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDIyNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FjOTNmOWQzNmQxNTZlZGViNDcxNGI5ZDJlNWQ5Yzk3NmNhYTg3ZTFmNjk2ODI5YTlkYjJjMzhjM2JmOGMxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JPq6tfVuao4DC_UClnzWVr67k7QrY4C0UQLQuwdUBGU)

我代码跑起来之后，也不行啊
![image](https://github.com/ant-design/ant-design-mini/assets/15991882/ad082880-b9c7-4693-a818-2bcca71ce53e)

**Comment by DiamondYuan** [comment]
> > > 我按照这个文档调整，怎么没有生效，可以给个示例代码吗
> > 
> > 
> > https://github.com/DiamondYuan/ant-design-mini-reproduce/tree/main/less
> > 可以用小程序开发工具打开这个项目。
> > ![image](https://private-user-images.githubusercontent.com/9692408/292947726-d19565d1-b5b3-45a2-847f-b5af10fd5aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzA1NDIsIm5iZiI6MTcwMzczMDI0MiwicGF0aCI6Ii85NjkyNDA4LzI5Mjk0NzcyNi1kMTk1NjVkMS1iNWIzLTQ1YTItODQ3Zi1iNWFmMTBmZDVhYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDIyNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FjOTNmOWQzNmQxNTZlZGViNDcxNGI5ZDJlNWQ5Yzk3NmNhYTg3ZTFmNjk2ODI5YTlkYjJjMzhjM2JmOGMxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JPq6tfVuao4DC_UClnzWVr67k7QrY4C0UQLQuwdUBGU)
> 
> 我代码跑起来之后，也不行啊 ![image](https://private-user-images.githubusercontent.com/15991882/293125560-ad082880-b9c7-4693-a818-2bcca71ce53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzE4OTQsIm5iZiI6MTcwMzczMTU5NCwicGF0aCI6Ii8xNTk5MTg4Mi8yOTMxMjU1NjAtYWQwODI4ODAtYjljNy00NjkzLWE4MTgtMmJjY2E3MWNlNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAyNDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZmM5NmQ1Y2VlNDAyZDQwZmY0NGExOTlmNzM1ZDRjYjg1NzIyZjdhYjBiMjE0MmNhNGFkYmQ3NGVlNTEzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HCTC5lX4oq2zlgFN08rfz8MNDng0dXGXyzXmg0AwqP8)


你的小程序开发者工具是什么版本的？ 升级到最新版试试看

**Comment by fangqibin** [comment]
> > > > 我按照这个文档调整，怎么没有生效，可以给个示例代码吗
> > > 
> > > 
> > > https://github.com/DiamondYuan/ant-design-mini-reproduce/tree/main/less
> > > 可以用小程序开发工具打开这个项目。
> > > ![image](https://private-user-images.githubusercontent.com/9692408/292947726-d19565d1-b5b3-45a2-847f-b5af10fd5aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzA1NDIsIm5iZiI6MTcwMzczMDI0MiwicGF0aCI6Ii85NjkyNDA4LzI5Mjk0NzcyNi1kMTk1NjVkMS1iNWIzLTQ1YTItODQ3Zi1iNWFmMTBmZDVhYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDIyNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FjOTNmOWQzNmQxNTZlZGViNDcxNGI5ZDJlNWQ5Yzk3NmNhYTg3ZTFmNjk2ODI5YTlkYjJjMzhjM2JmOGMxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JPq6tfVuao4DC_UClnzWVr67k7QrY4C0UQLQuwdUBGU)
> > 
> > 
> > 我代码跑起来之后，也不行啊 ![image](https://private-user-images.githubusercontent.com/15991882/293125560-ad082880-b9c7-4693-a818-2bcca71ce53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzE4OTQsIm5iZiI6MTcwMzczMTU5NCwicGF0aCI6Ii8xNTk5MTg4Mi8yOTMxMjU1NjAtYWQwODI4ODAtYjljNy00NjkzLWE4MTgtMmJjY2E3MWNlNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAyNDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZmM5NmQ1Y2VlNDAyZDQwZmY0NGExOTlmNzM1ZDRjYjg1NzIyZjdhYjBiMjE0MmNhNGFkYmQ3NGVlNTEzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HCTC5lX4oq2zlgFN08rfz8MNDng0dXGXyzXmg0AwqP8)
> 
> 你的小程序开发者工具是什么版本的？ 升级到最新版试试看

升级到新版可以了，谢谢。
