### ISSUE TITLE
range-picker在mpaas上报错，mixinValue不能使用

### ISSUE THREAD

**Issue by weiminghaoo** [ant-design/ant-design-mini#1014]
## 组件

range-picker
## 基础库版本

- [x] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

mpaas

## 组件库版本 

2.16.0
## 预期行为 
<img width="724" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/29938792/0e97c94c-1160-4461-bfe4-c9cdaac38cc4">

## 复现步骤 
``` axml
 <range-picker
        placeholder="请选择"
        defaultValue="{{defaultDateRange}}"
        onPickerChange="handlePickerRangeChange"
        onVisibleChange="handleTriggerPicker"
        onOk="handleRangeOk"
>
</range-picker>
```

**Comment by DiamondYuan** [comment]
没复现，请问是真机还是模拟器？
如果是内部用户，可以钉钉私聊我。

**Comment by weiminghaoo** [comment]
> 没复现，请问是真机还是模拟器？ 如果是内部用户，可以钉钉私聊我。

模拟器
<img width="512" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/29938792/413c8cfc-4696-4b85-a307-55387e37e8ca">
<img width="142" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/29938792/388dd5a8-ba70-4bb6-94ca-5cf4ad0e9fc7">

**Comment by ottomao** [comment]
这个基础库版本也太低了...

**Comment by weiminghaoo** [comment]
> 没复现，请问是真机还是模拟器？ 如果是内部用户，可以钉钉私聊我。

**Comment by weiminghaoo** [comment]
> 没复现，请问是真机还是模拟器？ 如果是内部用户，可以钉钉私聊我。

抱歉 我的问题
