### ISSUE TITLE
form组件报错

### ISSUE THREAD

**Issue by 125477** [ant-design/ant-design-mini#104]
## 背景
 
form组件报错，组件正常显示，输入也会报错，onValuesChange触发不了
![image](https://user-images.githubusercontent.com/51810441/168987492-e8376e9e-36be-4e3d-9d56-1a976650f480.png)
![image](https://user-images.githubusercontent.com/51810441/168987387-b961715c-c417-421d-8916-7dfce603e2d2.png)

**Comment by 125477** [comment]
form form="{{form}}" initialValues="{{initialValues}}" onValuesChange="handleValuesChange">
  <form-group radius header="发票详情">
    <form-item
      required
      label="抬头类型"
      name="name"
      form="{{form}}">
      <radio-group mode="form">
        <radio-item value="a1">单选一</radio-item>
        <radio-item value="a2">单选二</radio-item>
      </radio-group>
    </form-item>
</form-group>
</form>

**Comment by 125477** [comment]
<form form="{{form}}" initialValues="{{initialValues}}" onValuesChange="handleValuesChange">
  <form-group radius header="发票详情">
    <form-item
      required
      label="抬头类型"
      name="name"
      form="{{form}}">
      <radio-group mode="form">
        <radio-item value="a1">单选一</radio-item>
        <radio-item value="a2">单选二</radio-item>
      </radio-group>
    </form-item>

    <form-item
      required
      label="发票抬头"
      name="account"
      form="{{form}}">
      <input-item mode="form" placeholder="请输入账号"/>
    </form-item>
  </form-group>
</form>

**Comment by miaodongqing** [comment]
能提供最下复现demo吗？

**Comment by voidjay** [comment]
没有开启component2配置吧

**Comment by TusiziLy** [comment]
> 

请问怎么开启啊

**Comment by bzd-1** [comment]
> > 
> 
> 请问怎么开启啊

编辑器右上角的详情，里面有小程序配置
