### ISSUE TITLE
组件引入方式可否使用easycom？

### ISSUE THREAD

**Issue by deajax** [ant-design/ant-design-mini#1057]
## 背景
 
目前组件的命名还是驼峰，首字母大写，这样在easycom里的$1字段，无法识别大写字母导致找不到组件。

## 期望
 
希望组件能改为全小写

## 思路
 
组件命名改为全小写

**Comment by DiamondYuan** [comment]
easycom 应该只支持 vue 组件？ antd-mini 是小程序原生组件
