### ISSUE TITLE
List-ListItem 图标渲染两次

### ISSUE THREAD

**Issue by Kuntey** [ant-design/ant-design-mini#1069]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

微信小程序

## 预期行为 

只显示一个图标

## 复现步骤 

1. npm 安装 antd-mini 2.25.0
2. 构建npm
3. 复制示例代码

**Comment by DiamondYuan** [comment]
https://github.com/ant-design/ant-design-mini/pull/1072/files

感谢反馈，下个版本会修复这个问题。

目前可以用 Slot 来规避这个问题， 不要传 image 参数，使用 slot

 <ImageIcon slot="image"  image={image} className="ant-list-item-image" />

**Comment by Kuntey** [comment]
好的
