### ISSUE TITLE
Input和Button设置className后写样式没有作用

### ISSUE THREAD

**Issue by Kuntey** [ant-design/ant-design-mini#1077]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

微信小程序

## 组件库版本 

2.25.0

## 预期行为 

有作用

## 复现步骤 

1. 设置Input或Button的className属性
2.

**Comment by DiamondYuan** [comment]
https://ant-design-mini.antgroup.com/guide/faq#%E5%9C%A8%E6%94%AF%E4%BB%98%E5%AE%9D%E5%B0%8F%E7%A8%8B%E5%BA%8F-page-%E9%87%8C%E8%A6%86%E7%9B%96-antd-mini-%E7%9A%84%E6%A0%B7%E5%BC%8F%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by Kuntey** [comment]
是微信小程序版

**Comment by DiamondYuan** [comment]
> 是微信小程序版

我这边测试是有效的，能提供一个复现的小 demo 么。

**Comment by Kuntey** [comment]
```
<view class="search-bar-container">
    <van-dropdown-menu active-color="#1677ff">
        <van-dropdown-item value="{{ value1 }}" options="{{ option1 }}" />
        <van-dropdown-item id="item" title="{{ itemTitle }}">
            <view class="man-hour-wrap">
                <!-- Input的className没有效果 -->
                <a-input className="custom-color" placeholder="请输入最小值" bind:change="onChange" />
                -
                <!-- Input的className没有效果 -->
                <a-input className="custom-color" placeholder="请输入最大值" bind:change="onChange" />
            </view>
            <view style="padding: 5px 16px;">
                <!-- Button的className没有效果 -->
                <a-button type="primary" className="btn-round" style="width: 100%; font-size: 28rpx; border-radius: 50rpx;" bind:click="onConfirm">
                    确认
                </a-button>
            </view>
        </van-dropdown-item>
    </van-dropdown-menu>
</view>
```
因为没有提供dropdown下拉菜单的组件，所有使用了vant的下拉菜单

**Comment by DiamondYuan** [comment]
自定义样式与组件内部样式优先级不确定，为了确保自定义样式生效，可以试试看 !important

**Comment by Kuntey** [comment]
![image](https://github.com/ant-design/ant-design-mini/assets/70432310/fff87666-13fd-45cc-b43b-f515b66d71dc)
加了!important没有效果

**Comment by DiamondYuan** [comment]
> ![image](https://private-user-images.githubusercontent.com/70432310/301051737-fff87666-13fd-45cc-b43b-f515b66d71dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODAxMzcsIm5iZiI6MTcwNjY3OTgzNywicGF0aCI6Ii83MDQzMjMxMC8zMDEwNTE3MzctZmZmODc2NjYtMTNmZC00NWNjLWI0M2ItZjUxNWI2NmQ3MWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA1NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NTg0MDdlM2M2MzAzZmRjNTVjZDdjZGQwMzg0ODU3OGEyMDcyM2YxMmQwNTkyODQ4ODIyNzQ5NjUzMTRkYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1APTV4hULAAPDOAv0Aaz461ZFwufKKEnCui6ZAqX0Qc) 加了!important没有效果


能建一个最小复现 demo 吗？我这边没办法复现。

**Comment by Kuntey** [comment]
[antd-mini-demo.zip](https://github.com/ant-design/ant-design-mini/files/14108102/antd-mini-demo.zip)

**Comment by Kuntey** [comment]
好的，可以了，谢谢
