### ISSUE TITLE
form-picker 选择后获取不到值

### ISSUE THREAD

**Issue by Kuntey** [ant-design/ant-design-mini#1092]
## 组件

FormPicker
## 基础库版本
3.3.3

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

微信小程序
## 组件库版本 

2.27.0
## 预期行为 

能够获取到值
## 复现步骤 

1. 
2. 

## 复现 demo

[antd-mini-demo.zip](https://github.com/ant-design/ant-design-mini/files/14161057/antd-mini-demo.zip)

**Comment by DiamondYuan** [comment]
已修复，试试看 2.27.1
