### ISSUE TITLE
input 支持双行值显示

### ISSUE THREAD

**Issue by CrossLee** [ant-design/ant-design-mini#1095]
## 背景
用户在输入时，匹配上辅助值时需要同时显示，如图
<img width="304" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/4584905/1a293b32-25a0-443c-b736-946610c05e40">

## 期望
支持 tips 字段，作为辅助值显示

## 思路
参考 tdesign 组件

https://tdesign.tencent.com/miniprogram/components/input

<img width="1494" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/4584905/f550a724-7877-4f8a-ae91-f01be390318f">

**Comment by DiamondYuan** [comment]
![image](https://github.com/ant-design/ant-design-mini/assets/9692408/5ecc99f1-a594-4d64-bac2-6614a483726e)


```
  <FormInput
      label="地址"
      name="address"
      placeholder="请输入地址"
      allowClear
      help="显示帮助"
      ref="handleRef"
    ></FormInput>
```


可以使用 form-item 的 help 字段。
