### ISSUE TITLE
form-input 组件怎么设置只读模式

### ISSUE THREAD

**Issue by lff2018** [ant-design/ant-design-mini#1127]
1. form-input 组件怎么设置只读模式
2. 如果添加disabled禁用   css怎么设置默认样式呢

## 期望
可以设置只读模式  或者  设置disabled的默认样式

## 思路
修改了disabled的默认样式,但是没生效
 .ant-input-disabled {
        opacity: 1;
        color: #2B2B2B;
    }

**Comment by rayhomie** [comment]
我在demo中通过样式覆盖是可以实现对应的效果的

<img width="1018" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/63136891/bf3c55be-a374-4f30-8d68-2a306ae7731e">
