### ISSUE TITLE
小程序版tabbar增加Switchtab后切换异常

### ISSUE THREAD

**Issue by jingjianqian** [ant-design/ant-design-mini#1132]
![image](https://github.com/ant-design/ant-design-mini/assets/16252523/87ac75b0-493c-49cb-b898-ab79d19b2ec1)
是bug还是我的代码有问题，小程序切换tabbar需要点击两次，去掉Switchtab就正常

**Comment by DiamondYuan** [comment]
来一个复现的 demo

**Comment by jingjianqian** [comment]
https://github.com/jingjianqian/wechatApp/tree/master/guide

**Comment by DiamondYuan** [comment]
这个和 antd-mini 没关系.

可以参考下面的文档解决。

https://developers.weixin.qq.com/community/develop/doc/0002c4f1bf450029be4dd1c155b800

**Comment by jingjianqian** [comment]
感谢

**Comment by jingjianqian** [comment]
> 这个和 antd-mini 没关系.
> 
> 可以参考下面的文档解决。
> 
> https://developers.weixin.qq.com/community/develop/doc/0002c4f1bf450029be4dd1c155b800

感谢
