### ISSUE TITLE
Modal 在微信小程序里打开关闭没有过渡动画

### ISSUE THREAD

**Issue by Ttou** [ant-design/ant-design-mini#1138]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [x] iOS
- [x] Android
- [ ] HarmonyOS

## APP 

微信小程序

## 组件库版本 

2.28.3

## 预期行为 

Modal打开关闭时有过渡动画，与支付宝小程序下一致

## 复现 demo

![iShot_2024-04-05_15 43 51](https://github.com/ant-design/ant-design-mini/assets/4298437/afbefdb4-544e-49da-8408-ddfa34135e68)

**Comment by rayhomie** [comment]
npm install antd-mini@2.29.1
