### ISSUE TITLE
自定义表单组件如何设置默认值？

### ISSUE THREAD

**Issue by 11003** [ant-design/ant-design-mini#1141]
![ae3f976dcdcc54731c9480e9c917fa51](https://github.com/ant-design/ant-design-mini/assets/35055270/e0fac23a-6f1f-4f48-aad6-6df014154cb6)

**Comment by 11003** [comment]
this.form.setFieldValue('like', ['basketball','badminton'])

**Comment by rayhomie** [comment]
需要在Form实例化之后再去调用setFieldValue方法，onLoad中的话setTimeout试试

**Comment by 11003** [comment]
> 需要在Form实例化之后再去调用setFieldValue方法，onLoad中的话setTimeout试试

我组件里面的`formData.value`有值了，如何把`formData.value`正确赋值给图片列表`imageList`呢？
![image](https://github.com/ant-design/ant-design-mini/assets/35055270/21ddb4d9-bdd7-41ae-8c06-0a24b364e0d9)

**Comment by 11003** [comment]
修改了处理方法：

```js
didMount() {
		nextTick(() => {
			let data = this.getFormData()
			if (data.value) {
				this.setData({
					imageList: typeof data.value === 'string' ? [data.value] : data.value,
					statusArr: ['1']
				})
			}
		}, 300)
	},
```

**Comment by rayhomie** [comment]
`array.push`直接修改了小程序的`data`，不建议这样做。可以换成`[...statusArr, '1']`
