### ISSUE TITLE
ant-date-picker value值指定后。再清除deal_end为空是  前端数据无法清空

### ISSUE THREAD

**Issue by adrico** [ant-design/ant-design-mini#1191]
![image](https://github.com/ant-design/ant-design-mini/assets/5729242/442be334-4f60-43bb-ab3a-d1d6e9117ac4)
用户在未填写维修开始的情况下，优先填写维修结束。此时系统识别到，强行把维修结束的时间给清空掉。所用组件为ant-date-picker
前面用了一个for循环取出item
<ant-date-picker
            a:else
            slot="extra"
            disabled = "{{ item.deal_start && !item.deal_end?false:true }}"
            precision="minute"
            value = "{{item.deal_end}}"
            format="YYYY-MM-DD HH:mm"
            placeholder='选择时间'
            data-type="deal_end"
            data-index="{{index}}"
            data-id="{{item.id}}"
            data-dmid="{{item.deal_man_id}}"
            data-r_id="{{detailInfo.repair_id}}"
            onOk="MTimeEnd"
            />
发现按照这种逻辑,设置deal_end=''页面上无法将数据清空 setdata也不行。

**Comment by rayhomie** [comment]
提供一个最小能复现的demo，我看你的描述，理解不了你说的场景。
