### ISSUE TITLE
【微信小程序】form-stepper 如果使用键盘输入 没办法触发form表单的onValuesChange

### ISSUE THREAD

**Issue by baixiaosh** [ant-design/ant-design-mini#1193]
## 组件

FormStepper

## 基础库版本
微信基础库 3.4.4

## 设备机型
微信开发工具

## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS

## 组件库版本 

2.31.2

## 预期行为 

能正常触发onValuesChange

## 复现步骤 

1. 引入form-stepper组件
2.

**Comment by baixiaosh** [comment]
如果不设置初始值为数字类型，对应form表单的数据也不会更新

**Comment by rayhomie** [comment]
```js
   this.form.onValuesChange((changedValues, allValues) => {
      console.log(changedValues);
    });
```
<img width="897" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/63136891/22531c0f-faa2-46ba-9229-1c41080fae36">

我这边是正常work的
