### ISSUE TITLE
notice-bar 微信适配的 icon 插槽丢失

### ISSUE THREAD

**Issue by codesyofo** [ant-design/ant-design-mini#1194]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2.

**Comment by rayhomie** [comment]
微信不支持默认插槽。我这边看能否通过一个属性来控制，兼容你微信的这个场景

**Comment by codesyofo** [comment]
> 微信不支持默认插槽。我这边看能否通过一个属性来控制，兼容你微信的这个场景

可以对原有的字段 `icon` 的类型做处理吧，比如设置成 `boolean`，没必新加个字段
这样可否

**Comment by rayhomie** [comment]
> > 微信不支持默认插槽。我这边看能否通过一个属性来控制，兼容你微信的这个场景
> 
> 可以对原有的字段 `icon` 的类型做处理吧，比如设置成 `boolean`，没必新加个字段 这样可否

不能出现break change为了微信版本的插槽支持，而去影响支付宝版本的用法

**Comment by codesyofo** [comment]
> > > 微信不支持默认插槽。我这边看能否通过一个属性来控制，兼容你微信的这个场景
> > 
> > 
> > 可以对原有的字段 `icon` 的类型做处理吧，比如设置成 `boolean`，没必新加个字段 这样可否
> 
> 不能出现break change为了微信版本的插槽支持，而去影响支付宝版本的用法

`icon` 属性支付宝版本是 `string`，微信版本新增 `boolean`

**Comment by rayhomie** [comment]
要不辛苦你帮忙提个pr，我看看

**Comment by codesyofo** [comment]
另外问下项目用 `pnpm` 启动不了吗？我用 `pnpm dev`报错
![image](https://github.com/ant-design/ant-design-mini/assets/49975575/e85da40f-3e49-468d-acc2-eb897609068f)


> 要不辛苦你帮忙提个pr，我看看

**Comment by rayhomie** [comment]
> 另外问下项目用 `pnpm` 启动不了吗？我用 `pnpm dev`报错 ![image](https://private-user-images.githubusercontent.com/49975575/336769388-e85da40f-3e49-468d-acc2-eb897609068f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Nzg5MTEsIm5iZiI6MTcxNzU3ODYxMSwicGF0aCI6Ii80OTk3NTU3NS8zMzY3NjkzODgtZTg1ZGE0MGYtM2U0OS00NjhkLWFjYzItZWI4OTc2MDkwNjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA5MTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzkyMjBmNjMxYjljOWY0NGQwZDNmZTBjMTVkYmQ1ZjMxNzE5MWYyYmRkZGQ5NWM1Y2I1NWQwMTEzYWU3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4_WVo3E3GAKopVy4AgjcqFlzcz7vhWeLVOY5THE0co)
> 
> > 要不辛苦你帮忙提个pr，我看看
你先本地 `pnpm add @types/node -D`一下，可以解决，我后续把这个依赖添加上去

**Comment by codesyofo** [comment]
@rayhomie 装上后只编译了支付宝的
![image](https://github.com/ant-design/ant-design-mini/assets/49975575/66bf2bbc-99ee-4d70-a1a5-ccb3fc83db3c)
![image](https://github.com/ant-design/ant-design-mini/assets/49975575/28cb9685-c90c-4c0c-acb4-def3c438fc2d)

**Comment by codesyofo** [comment]
> @rayhomie 装上后只编译了支付宝的 ![image](https://private-user-images.githubusercontent.com/49975575/336783628-66bf2bbc-99ee-4d70-a1a5-ccb3fc83db3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODIzMDksIm5iZiI6MTcxNzU4MjAwOSwicGF0aCI6Ii80OTk3NTU3NS8zMzY3ODM2MjgtNjZiZjJiYmMtOTllZS00ZDcwLWExYTUtY2NiM2ZjODNkYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEwMDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2MxZTBhZWZhOTlmZmNjOTVmN2RkOWViZWRlODcxMjBhYzMyYzg1NDJhMjU5YzViZjgwMDg4OTdhODAzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wu3dikHThHUdfxeYwW5P8fyiMHChuIZ935zq2K5SRog) ![image](https://private-user-images.githubusercontent.com/49975575/336783771-28cb9685-c90c-4c0c-acb4-def3c438fc2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODIzMDksIm5iZiI6MTcxNzU4MjAwOSwicGF0aCI6Ii80OTk3NTU3NS8zMzY3ODM3NzEtMjhjYjk2ODUtYzkwYy00YzBjLWFjYjQtZGVmM2M0MzhmYzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEwMDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NDE1OWJkZmViOGEzOTRkN2YyNGI5YmUxMTM5YjI3ZDkyYjAyODkxZTk0YTdhMjcxODAwYjRmYjgxYWY1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sK5v7qK2mJD-t-UQ8I2fZ8OcWqmIwe1A1WRp_oC1ybk)

`node` 切回 20 可以了😭
