### ISSUE TITLE
Selector组件的value值只能取1到n(n为items的length)无法设为任意的string值(会失去选中效果及可能的其它效果)

### ISSUE THREAD

**Issue by xuda783380930** [ant-design/ant-design-mini#120]
## 基础库版本

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2. 

## 复现 demo

axml://<selector title="单选" value="1" items="{{items1}}"//>
js:Page({
  data: {
    items1: [
      { text: '选项一', value: '1' },
      { text: '选项二', value: '2' },
      { text: '选项三', value: '3' }]
}
});
json:{
  "defaultTitle": "Selector",
  "usingComponents": {
    "selector": "antd-mini-rpx/es/Selector/index",
  }
}
如果将js改为:
Page({
  data: {
    items1: [
      { text: '选项一', value: '11' },
      { text: '选项二', value: '12' },
      { text: '选项三', value: '13' }]
}
});
axml改为//<selector title="单选" value="12" items="{{items1}}"//>
预期第二个选择项被选中，实际没有选择项被选中

**Comment by miaodongqing** [comment]
0.0.14已修复
