### ISSUE TITLE
form-stepper组件

### ISSUE THREAD

**Issue by dwj-coder** [ant-design/ant-design-mini#1208]
## 背景
 
使用的时候步距属性step和默认值defaultValue属性无法实现，测试时stepper的输入框会多出上下调整数字的按钮，点击按钮之后数字会超出最大值和最小值的限制

## 期望
 
输入框中的按钮可以取消不使用，step和defaultValue属性能同步

**Comment by rayhomie** [comment]
form-stepper请通过 form实例去设置默认值
