### ISSUE TITLE
折叠面板需增加activeClassName类名

### ISSUE THREAD

**Issue by Zhou063** [ant-design/ant-design-mini#1221]
## 背景
 
需要动态给item添加类名
## 期望
 
增加一个activeClassName类名入口

**Comment by rayhomie** [comment]
<img width="668" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/63136891/3cefd3fd-1584-4d3e-83b2-5eaf14361715">

你动态改className是不是也可以实现
