### ISSUE TITLE
动态修改form-picker的disabled属性,form-picker状态不会及时更新,

### ISSUE THREAD

**Issue by YanFanCode** [ant-design/ant-design-mini#1231]
## 组件
form-picker组件

## 基础库版本

- [ ] 1.x
- [1 ] 2.x

## 手机系统

- [1 ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

钉钉小程序
## 组件库版本 
2.35.1

## 预期行为 
根据data内部的true和false,动态加载是否能点击弹出picker选择

## 复现步骤 

1. 绑定data内部布尔类型数据,在方法内部动态改变,页面上组件状态不更新,使用的this.setData()更新
2. 

## 复现 demo

xml
<form-picker
          class="item-ui"
          label="岗位"
          arrow
          name="post"
          disabled="{{disabledInfo}}"
          options="{{ postList }}"
          onVisibleChange="onVisibleChange"
          ref="handleRef"
        />
        
js: isThreeDaysAgo是一个方法 返回 true 或 false
if (isThreeDaysAgo(date)) {
      this.setData({
        isDelayFiling: true,
        disabledInfo: true
      })
    } else {
      this.setData({
        disabledInfo: false,
        isDelayFiling: false
      })
    }

**Comment by rayhomie** [comment]
<img width="303" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/63136891/6c25f3d9-0d5c-475b-afd1-cb14bd447632">
<img width="292" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/63136891/29bb409f-84a8-4193-94d2-9fafd314f969">

我这边正常的。

```axml
<view class="editorial_staff">
  <view class="editorial_scroll">
    <scroll-view scroll-y class="editorial_info">
      <form-picker
        label="水果"
        arrow
        name="fruit"
        options="{{ fruitList }}"
        ref="handleRef" 
        disabled="{{pickerDisabled}}"
        />
        pickerDisabled:{{pickerDisabled}}
    </scroll-view>
  </view>
  <view class="editorial_btn">
    <ant-button type="primary" onTap="dis">
      改变pickerDisabled
    </ant-button>
  </view>
</view>
```
```js
import {
  Form
} from 'antd-mini/es/Form/form';

Page({
  data: {
    fruitList: ['苹果', '香蕉', '橘子', '西瓜'],
    pickerDisabled: false,
  },
  onLoad() {
    this.form = new Form();
  },
  handleRef(ref) {
    this.form.addItem(ref);
  },
  dis() {
    const {
      pickerDisabled
    } = this.data

    this.setData({
      pickerDisabled: !pickerDisabled
    })
  }
});
```
