### ISSUE TITLE
Picker  0 不显示

### ISSUE THREAD

**Issue by xyh569923911** [ant-design/ant-design-mini#1234]
### 0 不会显示
***a:if="{{ placeholder }}"    class="ant-picker-value-placeholder"  {{ placeholder }}***

**Comment by rayhomie** [comment]
看不太懂，需要描述清楚一点

**Comment by xyh569923911** [comment]
> 看不懂，描述清楚一点



> 看不太懂，需要描述清楚一点

#
![微信截图_20240704164006](https://github.com/ant-design/ant-design-mini/assets/37889620/2dac00c2-ec42-4a44-a94e-6d067c864ee8)
这里会导致选择0 的时候不显示

**Comment by rayhomie** [comment]
placeholder你传'0'字符串
