### ISSUE TITLE
uni-app脚手架模式中引入组件在项目编译时会经常出现如下报错，在尝试多次后就不报错，可每次拉取项目时又会报错

### ISSUE THREAD

**Issue by laoxiaokang** [ant-design/ant-design-mini#1243]
![ab3d78ef516531882f0c670ed8dab7e](https://github.com/user-attachments/assets/d4e7267a-1560-4fd8-a826-b8155e6f0b98)

**Comment by rayhomie** [comment]
提给uniapp吧，应该是他们那边预编译过程有问题导致的
