### ISSUE TITLE
Input组件设置为allowClear时，聚焦状态下无法清空输入框的值，失焦后可以清空。

### ISSUE THREAD

**Issue by Moonofweisheng** [ant-design/ant-design-mini#1255]
## 组件

input组件

## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [x] Android
- [x] HarmonyOS

## APP 

支付宝
## 组件库版本 

2.25.0
## 预期行为 

可清空输入框聚焦后输入文字，点击清空按钮可以清空输入内容
## 复现步骤 

1. 设置input组件为allowClear，在输入框内无值时点击输入框聚焦输入文字，然后聚焦状态点击清空按钮，此时无法清除输入内容，可以参见下方视频，从观测上是聚焦后有内容显示clear图标，但是此时输入框实际宽度仍是未显示clear图标的宽度，从视频最后输入框内容超出输入框时会显示在clear图标上可以看出，失焦后清空按钮就可以工作了。

https://github.com/user-attachments/assets/cf55fff0-d1af-4054-a8b1-f9cf3ec9abf8

## 复现 demo

```html
 <ant-input
    placeholder="请输入内容"
    allowClear />
```

**Comment by rayhomie** [comment]
最新的版本应该已经把 清空按钮 和输入框之间加了左边距

**Comment by rayhomie** [comment]
enableNative="{{true}}"
