### ISSUE TITLE
popup组件及继承者Modal 把右上角关闭按钮的大小透出吧

### ISSUE THREAD

**Issue by wkii** [ant-design/ant-design-mini#126]
## 背景
 
popup组件的源代码，关闭按钮部分，默认写成了x-small：
```js
 <view class="amd-popup-close-container" a:if="{{showCloseIcon}}">
    <icon type="CloseOutline" size="x-small" onTap="onClose"/>
  </view>
```

## 期望
 
popup组件的关闭按钮，默认写成了x-small，这个属性放开可配轩吧。同样，Modal也是。
这个默认的尺寸有点小，不太好点击。

**Comment by miaodongqing** [comment]
0.0.14 右上角close大小已调整, 由于close按钮自定义大小的场景较少， props层不予支持
