### ISSUE TITLE
ActionSheet的取消按钮会被TabBar组件遮挡

### ISSUE THREAD

**Issue by wvfeng** [ant-design/ant-design-mini#1265]
## 组件
ActionSheet

## 基础库版本

- [x] 3.5.1

## 设备机型

- 微信开发者工具
- iPhone 14 Pro

## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 
微信小程序

## 组件库版本 
2.36.4

## 预期行为 
![image](https://github.com/user-attachments/assets/e4ce9225-7d13-4811-9e13-9e7a9df6b6b1)

取消按钮在最上层，以便于用户点击

## 复现步骤 
1. 使用npm初始化package.json
2. 安装antd-mini组件
3. 工具 --> 构建npm
4. [按照文档引入TabBar](https://ant-design-mini.antgroup.com/components/tab-bar)
5. [引入Button和ActionSheet组件，并按照文档使用组件](https://ant-design-mini.antgroup.com/components/action-sheet)
6. 通过按钮打开ActionSheet即可复现

## 语法错误问题与解决
2.36.4版本在微信小程序构建后会收到一个错误提示
![image](https://github.com/user-attachments/assets/fbb98211-a628-4f6b-b180-fc04cc7841c9)
只需要找到这个文件并修复语法错误即可
修改前
![image](https://github.com/user-attachments/assets/77b468d5-2d44-4072-8c0f-6f0d44bc0539)
修改后
![image](https://github.com/user-attachments/assets/ecae8fcd-62a3-4a41-b6e2-4d6fbab59f55)

## 复现 demo

 > 我上传的demo中已经按照复现步骤制作完毕，并且修复了上述语法错误问题

[ActionSheetDemo.zip](https://github.com/user-attachments/files/16632132/ActionSheetDemo.zip)

**Comment by rayhomie** [comment]
wxs的问题，我会今天修复。
ActionSheet的取消按钮会被TabBar组件遮挡，可能需要自行调整一下组件样式层级关系

**Comment by wvfeng** [comment]
> wxs的问题，我会今天修复。 ActionSheet的取消按钮会被TabBar组件遮挡，可能需要自行调整一下组件样式层级关系

![image](https://github.com/user-attachments/assets/6ec89664-1bfb-4950-aced-2eeabd3fa07f)
通过调试我发现组件上的默认层级是998，把这个层级调整到10000或以上是可以显示取消按钮的，但是除非修改源码，否则我没把发覆盖这个配置，我尝试使用className给取消按钮所在的类ant-actionsheet-cancel，覆盖一个z-index属性，但是失败了，即便是把z-index设置到很大也不能让取消按钮显示到前面

**Comment by rayhomie** [comment]
2.36.5 我会给action-sheet组件新增zIndex属性，你去改这个属性吧

**Comment by wvfeng** [comment]
> 2.36.5 我会给action-sheet组件新增zIndex属性，你去改这个属性吧

好的 👍👍👍
这个版本预计什么时候发布？

**Comment by rayhomie** [comment]
最迟本周五

**Comment by rayhomie** [comment]
> > 2.36.5 我会给action-sheet组件新增zIndex属性，你去改这个属性吧
> 
> 好的 👍👍👍 这个版本预计什么时候发布？

2.36.5 已经发布

**Comment by wvfeng** [comment]
> > > 2.36.5 我会给action-sheet组件新增zIndex属性，你去改这个属性吧
> > 
> > 
> > 好的 👍👍👍 这个版本预计什么时候发布？
> 
> 2.36.5 已经发布

![image](https://github.com/user-attachments/assets/70ab3d58-39f9-451c-9c73-1b53e37d45ab)

是不是发布的时候遗漏了zIndex，我留意到你提交的PR里面是加了这个变量的，但是我这边正常升级后这个变量并不存在，这样会导致层级丢失，最终使用了popup 的默认层级998
![image](https://github.com/user-attachments/assets/a3ca6aa6-ba4f-4ab7-9e37-a327af88ea59)

**Comment by wvfeng** [comment]
> > > > 2.36.5 我会给action-sheet组件新增zIndex属性，你去改这个属性吧
> > > 
> > > 
> > > 好的 👍👍👍 这个版本预计什么时候发布？
> > 
> > 
> > 2.36.5 已经发布
> 
> ![image](https://private-user-images.githubusercontent.com/33809027/359346857-70ab3d58-39f9-451c-9c73-1b53e37d45ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzIwNzAsIm5iZiI6MTcyNDEzMTc3MCwicGF0aCI6Ii8zMzgwOTAyNy8zNTkzNDY4NTctNzBhYjNkNTgtMzlmOS00NTFjLTljNzMtMWI1M2UzN2Q0NWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA1MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2M5NTU0ZTFmNzg4YjEwM2IxOTgyYTU1MDYyMjM5NGI5NjhhMDFhYTYyMjY5YjM4N2U5MzA2OTQ0NjM3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UDTXU876J898DM-8IDW7oFxhLf7VCryXbIe2XExES1s)
> 
> 是不是发布的时候遗漏了zIndex，我留意到你提交的PR里面是加了这个变量的，但是我这边正常升级后这个变量并不存在，这样会导致层级丢失，最终使用了popup 的默认层级998 ![image](https://private-user-images.githubusercontent.com/33809027/359347586-a3ca6aa6-ba4f-4ab7-9e37-a327af88ea59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzIwNzAsIm5iZiI6MTcyNDEzMTc3MCwicGF0aCI6Ii8zMzgwOTAyNy8zNTkzNDc1ODYtYTNjYTZhYTYtYmE0Zi00YWI3LTllMzctYTMyN2FmODhlYTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA1MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMDJmYmQzY2Y1OTdiODQ4ZDIyYTJiZjcxNTVkODc2MDNhN2M5MDc4MTkwNzYwYzAxMzk0ZTg1ZDhmMTNiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9A1eYp4KAL9xC4ep84hE4xNuctCdx4yDWumewafyVKk)

经过测试手动添加这个变量定义可以解决这个问题，结果如下
![image](https://github.com/user-attachments/assets/0209779d-8602-4e1c-a562-e462ef898352)

**Comment by rayhomie** [comment]
你先通过 .ant-actionsheet-popup { z-index:10000 !important; } 这样处理你的场景吧

**Comment by wvfeng** [comment]
> 你先通过 .ant-actionsheet-popup { z-index:10000 !important; } 这样处理你的场景吧

好的，经过测试这个方案可以解决问题
