### ISSUE TITLE
希望增加单选项的filter 筛选卡

### ISSUE THREAD

**Issue by wkii** [ant-design/ant-design-mini#153]
## 背景
 
有时候只有一个选项，并且不想强烈的将各个选项展示，所以用filter好一些。

## 期望
 
希望有单选项的Filter，即左边是描述文字，右边是选项。

为什么想用Filter？ 因为普通的单选项太傻了，不能定义text和value。 比如原生的my.optionsSelect。
而且，私以为全屏弹出个选项上下滑选某一个类型，这种交互是小屏时代的产物。一点也不酷。

**Comment by miaodongqing** [comment]
听上去RadioBoxGroup能满足诉求
