### ISSUE TITLE
Selector 选择组 希望增加必须选择一项的功能

### ISSUE THREAD

**Issue by wkii** [ant-design/ant-design-mini#156]
## 背景
 
Selector 选择组，已经选中一项，再点一下就没了。 也没有onTap事件可以去做限制。
试了半天各种方法也不行。

## 期望
 
期望 Selector 选择组 能有至少选择一项，不能全部勾选掉的选项。

**Comment by Alpsli** [comment]
这个目前可以通过受控的方式实现

**Comment by miaodongqing** [comment]
0.0.19 已增加 minSelelctedCount
