### ISSUE TITLE
什么时候会有日历组件？

### ISSUE THREAD

**Issue by hanf1990** [ant-design/ant-design-mini#160]
## 背景
 
时间选择

## 期望
 
类似于antd 的Calendar组件

**Comment by Sxs7513** [comment]
正在开发中，预计七月底上线，请耐心等待哦

**Comment by hanf1990** [comment]
> 正在开发中，预计七月底上线，请耐心等待哦

好的。正式版本什么时候上线？准备替换掉之前的

**Comment by Alpsli** [comment]
https://github.com/ant-design/ant-design-mini/pull/188
