### ISSUE TITLE
图片上传bug

### ISSUE THREAD

**Issue by Shuzhenzhou123** [ant-design/ant-design-mini#170]
index.js文件下的44行
chooseImageRes.tempFiles.map应该为chooseImageRes.tempFilePaths.map

**Comment by Alpsli** [comment]
![image](https://user-images.githubusercontent.com/52439609/176581618-c43af8cc-a102-40dc-8a24-bedf274063bf.png)，
tempFilePaths 是拿不到图片size的，tempFiles是能够拿到图片size的 https://opendocs.alipay.com/mini/api/media/image/my.chooseimage
