### ISSUE TITLE
可不可以在事件Closures自定义传值

### ISSUE THREAD

**Issue by eyouhi** [ant-design/ant-design-mini#171]
如题，一般组件的事件函数是 `(value)=>{}`  
当遇到
```axml
   <view a:for = {{someArr}} >
            <SomeCompon          onChange="handleArr" />
   </view>
```

```javascript
    Page({
         data:{someArr:[{id:0,value:0},{id:1,value:0}]},
         handleArr(data){
                //Todo 如何根据点击的id的value变为data？
          }
    })
```
可不可以事件函数修改为
```
(value,data) => {}
```
其中data 为 axml 中 data-index 或data - id等赋值为
```
 {id:123,index:321}
```

_Originally posted by @eyouhi in https://github.com/ant-design/ant-design-mini/discussions/169_

**Comment by miaodongqing** [comment]
一般，最后一个参数是event， 通过event.target.dataset可以拿到组件的dataset。 目前不是所有事件类型都支持event，按需完善中

**Comment by eyouhi** [comment]
> 

也就是说目前的设计是 `(value,event)=>{}` ，只是某些组件还没完善到这个地步吗

**Comment by miaodongqing** [comment]
对， 后面信息输入下的组件会全部增加event支持
