### ISSUE TITLE
后期是否会支持微信小程序

### ISSUE THREAD

**Issue by WangXang** [ant-design/ant-design-mini#18]
## 背景
 
目前使用remaxjs，主要搭配vant 组件库开发微信小程序，请问ant-design-mini未来考虑支持微信小程序么？

## 期望
 
目前使用remaxjs，主要搭配vant 组件库开发微信小程序，请问ant-design-mini未来考虑支持微信小程序么？

**Comment by Simplyme0823** [comment]
我的理解是，remaxjs 是支持整个应用转换成小程序的。我不知道你说的支持微信小程序，是你想在 remaxjs 中使用 antd-mini，最后整个应用转成小程序。还是说，antd-mini 的每个组件都转换成微信小程序，当你你写原生的微信小程序的时候，就可以直接使用 antd-mini 组件？

**Comment by WangXang** [comment]
在 remaxjs 中使用 ant-design-mini ui组件，然后应用转成小程序

**Comment by Simplyme0823** [comment]
> 在 remaxjs 中使用 ant-design-mini ui组件，然后应用转成小程序

这个需求第一次碰到，没有调研过，成本上评估一下~

**Comment by miaodongqing** [comment]
22年不会～～

**Comment by haobarry** [comment]
同需求  如果能支持微信就好了,

**Comment by xiaofuliang** [comment]
同需求，要是支持remaxjs ，那样就可以转微信小程序了

**Comment by Jairwin-L** [comment]
> 同需求 如果能支持微信就好了,

+ 1

**Comment by jyforward** [comment]
可以支持原生的微信小程序吗
