### ISSUE TITLE
antd   tabs  + picker 导致fixed布局失效

### ISSUE THREAD

**Issue by 2449847346** [ant-design/ant-design-mini#190]
## 组件

tabs + picker

## 基础库版本

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

钉钉小程序

## 组件库版本 

0.0.18

## 预期行为 

picker弹窗在页面最上级

## 复现步骤 

1. 创建tabs 和tab-content
2. tab-content中创建picker
3. 打开picker可复现

## 复现 demo

目前已自行解决，transform删除，位移改用position:relative; left进行修改位置

**Comment by jc9702507** [comment]
#305
