### ISSUE TITLE
CollapseItem和ListItem 渲染列表 追加新数据时渲染页面失败

### ISSUE THREAD

**Issue by Tuesdaylxx** [ant-design/ant-design-mini#201]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

支付宝小程序

## 组件库版本 

0.0.18

## 预期行为 

首次渲染数据成功,如果再像数组中追加新数据,会跳转到一个页面 "页面遇到一些小问题,建议退出小程序后重新进入"
控制台没有报错

## 复现步骤 

1. CollapseItem或ListItem组件 使用a:for渲染数组
2. 点击加载更多,向数组中追加新数据,导致跳转页面

## 复现 demo

.axml
```
<collapse 
      className="demo-collapse" 
      uid="collapse-2" 
      accordion="{{false}}">
      <collapse-item a:for="{{testlist}}" a:key="*this"
        title="第一项" 
        uid="collapse-2" 
        name="{{index.toString()}}">
        这里是第一项的内容
      </collapse-item>
<collapse> 
```
.js
```
let test = []
Page({
data: {
    testlist:[]
  },
loadMore(){
    test.push(1,2)
    this.setData({
      testlist: test
    })
  },
})
 ```

**Comment by Alpsli** [comment]
你的这个 loadMore 需要调整下

**Comment by Tuesdaylxx** [comment]
请问需要怎么调整啊

**Comment by Tuesdaylxx** [comment]
是我开启了component2编译,不开启没问题的

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305
