### ISSUE TITLE
Tabs标签页中的TabItem的属性tab，类型中有badge?: number;，但是没有任何效果

### ISSUE THREAD

**Issue by zqq980214** [ant-design/ant-design-mini#206]
## 背景
 
Tabs标签页中的TabItem的属性tab，类型中有badge?: number;，但是没有任何效果

## 期望
 
希望能有徽标功能

**Comment by hanf1990** [comment]
+1
徽标的数量可以自定义，不能多了就显示省略号

**Comment by hanf1990** [comment]
自定义选中颜色，之前的mini-ali-ui都是有的

**Comment by miaodongqing** [comment]
> +1 徽标的数量可以自定义，不能多了就显示省略号

具体是指？

**Comment by miaodongqing** [comment]
> 自定义选中颜色，之前的mini-ali-ui都是有的

tab自定义选中颜色？

**Comment by miaodongqing** [comment]
0.0.21 tabs 已支持badge
