### ISSUE TITLE
list-item组件 extraBrief参数判断不严谨

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-mini#210]
list-item组件 extraBrief参数判断不严谨
当传进去是数字0的时候会被判断为false。应该兼容数字类型。
extra也是同样的问题

**Comment by jc9702507** [comment]
#305 会修改props

**Comment by jc9702507** [comment]
需要更严谨的判断，包括其他组件使用相同的props判断

**Comment by jc9702507** [comment]
1.0 修改了这个问题，使用slot
