### ISSUE TITLE
Form表单设置字段值

### ISSUE THREAD

**Issue by bzd-1** [ant-design/ant-design-mini#222]
## 背景
 
一个选择框，只要选择框的值一发生改变就清空其他的form-item的值，调用方法setFieldsValue方法进行重置之后会,如果传的有空值就会触发必填项的表单验证

## 期望
 
设置空值之后不会触发必填项的验证

## 思路
 
![image](https://user-images.githubusercontent.com/68361950/184050853-f704150b-9a35-47b5-baa4-9385dd6184f9.png)
可以的话注释掉修改字段值之后不需要进行验证，但是需要考虑到重置掉值之后如何清除掉所涉及字段之前的验证

**Comment by Alpsli** [comment]
我们正在重构form中

**Comment by T-yang857** [comment]
哇  这个问题啥时候能解决呀。想用form用不起来。太糟心了。

**Comment by zhouhua1818** [comment]
具体什么时候能弄好啊？

**Comment by jc9702507** [comment]
#305 
使用1.0表单组件https://ant-design-mini.antgroup.com/components/form
