### ISSUE TITLE
处于禁用状态的组件，点击能有事件暴露

### ISSUE THREAD

**Issue by rayhomie** [ant-design/ant-design-mini#227]
## 背景
 
checkbox或者按钮等组件，处于被禁用的状态时，想做Toast提示用户为什么当前操作后，按钮被禁用了

## 期望
 
期望可以disabled状态的按钮或各种组件，点击之后有事件暴露

**Comment by jc9702507** [comment]
禁用状态不可点击，小程序的基础组件里checkbox disabled就是无法点击及onChange。要是需要做提示，可以不用disabled，用户点击之后去判断是否可点击，再给提示
