### ISSUE TITLE
List组件优化，ListItem的左侧图片支持本地加载

### ISSUE THREAD

**Issue by bzd-1** [ant-design/ant-design-mini#234]
## 背景
 
渲染List列表的时候需要显示左侧的图片，目前仅支持icon图标，http格式的图片，不支持https和本地资源的图片

## 期望
 
希望能支持本地图片以及https格式的图片

## 思路
 
![image](https://user-images.githubusercontent.com/68361950/185347362-4cba39ef-d0be-4584-83ae-e6914438f9ec.png)
问题大致出在这个位置，因为这里就只进行了http的判断，其余的都默认为icon图标，所以在页面上渲染的时候会把本地资源或者https的图片当做icon来进行渲染，解决方法就是单独判断传进来的img是否是icon图标，如果是就进行渲染icon图标，如果不是就直接渲染为正常图片即可，至于https格式的图片需要注意一下

**Comment by Alpsli** [comment]
目前只是不支持本地图片，^http 是能够匹配到 https 哦

**Comment by bzd-1** [comment]
> 目前只是不支持本地图片，^http 是能够匹配到 https 哦

喔喔，我刚刚试了一下，https又起作用了，之前可能弄错了。那后面会支持本地图片吗？

**Comment by Alpsli** [comment]
建议还是把图片上传到cdn上去，不过如果实在需要，我们可以考虑支持本地图片

**Comment by bzd-1** [comment]
> 建议还是把图片上传到cdn上去，不过如果实在需要，我们可以考虑支持本地图片

喔喔，了解，看看后期这种需求多不，再考虑加上吧。

**Comment by Alpsli** [comment]
好的，我先关掉issue了哈
