### ISSUE TITLE
DatePicker 时间选择器,能选择60分60秒吗？

### ISSUE THREAD

**Issue by bzd-1** [ant-design/ant-design-mini#235]
## 组件

DatePicker
![image](https://user-images.githubusercontent.com/68361950/185533949-cf35b046-4f7c-42cf-a6e8-7e69e8c35d32.png)

看了一下源码，是设计成这样的
![image](https://user-images.githubusercontent.com/68361950/185536155-c47192a3-b04c-4ee2-9c5c-79683d706f9c.png)

## 基础库版本

- [ ] 2.7.19

## 设备机型
小程序开发者工具以及OPPO R17预览以及真机调试皆有

## 手机系统

- [ ] Android

## APP 

支付宝小程序

## 组件库版本 

0.0.20

## 预期行为 

正常情况应该是选择0分0秒至59分59秒，但是现在确可以选择60分60秒

## 复现步骤 

1. 设置precision属性为second
2. 在弹出的选框中即可复现

**Comment by Alpsli** [comment]
好的，我们修复下
