### ISSUE TITLE
tabbar图片模式下active问题

### ISSUE THREAD

**Issue by BaoGuoSen** [ant-design/ant-design-mini#236]
## 组件

TabBar

## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [x] iOS
- [x] Android
- [ ] HarmonyOS

## 组件库版本 

antd-mini 0.0.20

## 预期行为 

icon 为图片，一张是没选中的，一张是选中状态的，不管怎么切换始终是选中状态的图片，预期是切换不同的tab能显示两种状态的图片
## 复现步骤 

1. 
2.

**Comment by Alpsli** [comment]
麻烦提供下最小复现demo
