### ISSUE TITLE
container headerRight slot 无效

### ISSUE THREAD

**Issue by hzhoup** [ant-design/ant-design-mini#238]
<container title="标题" titleImage="{{titleImage}}" icon="HeartOutline" headerInBox="{{true}}">
  <view slot="headerRight">右部内容</view>
   <view class="box1">
    
  </view>
</container>

不好意思一直上传不了图片，示例代码直接贴上去不显示右部内容，控制台 DOM 也为空。

**Comment by hzhoup** [comment]
`<container title="标题" titleImage="{{titleImage}}" icon="HeartOutline" headerInBox="{{true}}">
    <view slot="headerRight">右部内容</view>
     <view class="box1">
      
    </view>
  </container>`

**Comment by Alpsli** [comment]
贴下最小复现demo以及你的基础组件库版本

**Comment by hzhoup** [comment]
```html
<container title="服务单号：SA2022080882">
  <view slot="headerRight">右部内容</view>
  <view>
    sss
  </view>
</container>
```

基础库版本：1.25.7

**Comment by hzhoup** [comment]
目标平台是钉钉小程序，但切换支付宝小程序也一样不显示

**Comment by Alpsli** [comment]
基础库版本低了，到服务群问问

**Comment by hzhoup** [comment]
- 如果版本号大于 1.24.0 ，说明当前是 V2 引擎

但在钉钉好像这个版本基础库不低了

**Comment by BillyKingChina** [comment]
同样碰到此问题，哪个是基础库哦

**Comment by lcop957** [comment]
一样的问题，请问解决了吗

**Comment by BillyKingChina** [comment]
解决了：（项目是浙政钉，基础库也很低只有1.4，想升级也无门，GRD几乎没人维护）
1.定位文件：“\node_modules\antd-mini\es\Container\ContainerHeader\index.axml”，第18行
2. <slot/>改为：<slot name="headerRight"></slot>
3. 小程序开发者工具 ，编译按钮 ，停止编译，在启动编译，刷新开效果

**Comment by jc9702507** [comment]
```html
<view 
  class="amd-container-header-right"
>
  <slot />
</view>
```
是修改为什么呢

**Comment by BillyKingChina** [comment]
> ```
> <view 
>   class="amd-container-header-right"
> >
>   <slot />
> </view>
> ```
> 
> 是修改为什么呢

不会用，html代码屏蔽了

**Comment by jc9702507** [comment]
![image](https://user-images.githubusercontent.com/113670357/197707970-f7fe3b79-b8cd-402e-b78c-44ad094571f6.png)

**Comment by lcop957** [comment]
> 解决了：（项目是浙政钉，基础库也很低只有1.4，想升级也无门，GRD几乎没人维护，似乎跟基础库无关） 1.定位文件：`“\node_modules\antd-mini\es\Container\ContainerHeader\index.axml”`，第18行 2.`<slot/>` 改为：`<slot name="headerRight"></slot>` 3. 小程序开发者工具 ，编译按钮 ，停止编译，再启动编译，刷新开效果
也就能临时用吧，还是得官方把包里的源码改掉；这个组件太多bug跟不完善的地方了

**Comment by jc9702507** [comment]
这个组件看起来有bug，需要修改props
#305
