### ISSUE TITLE
RadioGroup选中图标展示过大

### ISSUE THREAD

**Issue by guoping007** [ant-design/ant-design-mini#240]
## 组件
RadioGroup

## 基础库版本

- [ ] 1.x
- [* ] 2.x

## 手机系统

- [* ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 
支付宝小程序

## 组件库版本 
0.0.20

## 预期行为 
在0.0.10版本
选中后图标展示正常
![1661150520508_78D7CC43-4263-436c-A0AA-A8756A4BC9E0](https://user-images.githubusercontent.com/5616627/185857820-99be6a6c-6503-4b15-b45d-258363286dc0.png)

在0.0.11版本后
选中图标展示较大
![lQLPJxadPP8VLcrMnM0BlLA84X48rdP-fgMCr3vsAIQA_404_156](https://user-images.githubusercontent.com/5616627/185857765-60df2f0b-d662-4509-a67e-1e3bb9b78735.png)

**Comment by miaodongqing** [comment]
https://mini.ant.design/components/radio-group
官网示例大小是正常的，烦请给出最下示例demo

**Comment by guoping007** [comment]
知道问题，如果页面不引入 "icon": "antd-mini/es/Icon/index", 选中图标就会比较大
//test.json
{
  "usingComponents": {"collapse": "antd-mini/es/Collapse/index",
    "collapse-item": "antd-mini/es/Collapse/CollapseItem/index",
    "radio-group": "antd-mini/es/RadioGroup/index",
    "radio-item": "antd-mini/es/RadioGroup/RadioItem/index",
    "button": "antd-mini/es/Button/index"}
}

//test.axml
<view>
 
   
    <radio-group  
    value="选项二"
    data-value="value"
    uid="basic"
    onChange="handleChange">
    <radio-item a:for="{{list}}" value="{{item.value}}" uid="basic">{{item.label}}</radio-item >
  </radio-group>
   
</view>

//test.js

Page({
  data: { list: [
    { value: 'apple', label: '苹果' },
    { value: 'orange', label: '橘子' },
    { value: 'banana', label: '香蕉' },
  ],
    name: ['item-1'],
  }
});

**Comment by wyj580231** [comment]
提供个最小复现demo呢，按照上面的写法复现不出

**Comment by guoping007** [comment]
我再新项目上测试也无法复现，可能是现有项目样式冲突了，麻烦你了，要不你现关闭这个把，谢谢了

**Comment by jc9702507** [comment]
https://ant-design-mini.antgroup.com/components/checkbox

**Comment by jc9702507** [comment]
#305
