### ISSUE TITLE
Collapse 折叠面板-代码示例的受控模式点击【随机展开一项】无任何效果

### ISSUE THREAD

**Issue by guoping007** [ant-design/ant-design-mini#242]
## 基础库版本

- [ ] 1.x
- [* ] 2.x

## 手机系统

- [* ] iOS
- [ ] Android
- [ ] HarmonyOS

 

## 组件库版本 
0.0.20

## 复现步骤 

1. 
2. 

## 复现 demo
Collapse 折叠面板-代码示例的受控模式点击【随机展开一项】无任何效果

**Comment by kuromi-yl** [comment]
看了下，是Collapse的受控模式并为生效，这个稍后修复下

**Comment by kuromi-yl** [comment]
从代码总看，是Collapse的受控模式并未生效，这个稍后修复下

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305

**Comment by jc9702507** [comment]
1.0 这个问题解决
