### ISSUE TITLE
Filter 筛选卡不支持默认初始值

### ISSUE THREAD

**Issue by whace** [ant-design/ant-design-mini#244]
## 背景
 
我们希望Filter 默认值为items的第一个，好像给value赋值，没有效果，面板中是选中的，但是界面显示的依然是placeholder.

## 期望
 
希望添加一个 defaultValue的选项

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305

**Comment by jc9702507** [comment]
这个组件会去掉

**Comment by jc9702507** [comment]
这个是selector + dropdown，不属于通用组件

**Comment by juneswang2016** [comment]
这个组件以后不能使用了么？去掉后用什么代替？

**Comment by jc9702507** [comment]
#507

**Comment by jc9702507** [comment]
这个组件去掉了，使用 https://ant-design-mini.antgroup.com/components/selector#%E4%BD%BF%E7%94%A8selector%E8%87%AA%E5%AE%9A%E4%B9%89filter
