### ISSUE TITLE
钉钉小程序使用uploader组件

### ISSUE THREAD

**Issue by adrico** [ant-design/ant-design-mini#251]
## 组件

uploader
## 基础库版本
1.25.7

- [ ] 1.x
- [ ] 2.x

## 设备机型
iPhone12
## 手机系统
iOS
- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 预期行为 

上传图片
## 复现步骤 

1. uploader图片时候 点击submit报错
2.

**Comment by Alpsli** [comment]
https://github.com/ant-design/ant-design-mini/pull/253

**Comment by Alpsli** [comment]
已解决
