### ISSUE TITLE
popup 组件支持内容a:show而不是a:if

### ISSUE THREAD

**Issue by shuizhongxiong** [ant-design/ant-design-mini#265]
## 背景
popup 弹窗内容是一个无线滚动列表，当滚动了100+条数据后，点击关闭后，页面直接卡死，过一会才会正常交互。

## 期望 & 思路
目前想到的办法是，将 a:if 改成 a:show 问题是可以解决的，希望组件能支持。当然，如果有更好的办法也可以哈～

**Comment by Alpsli** [comment]
你可以在picker里面content自己用 a:if 的

**Comment by shuizhongxiong** [comment]
我自己 a:If 没用，因为组件外层用的还是 a:if，现在的问题是 a:if 里如果有很多 view 的时候，状态切换页面会卡住，该用 a:show 才可以。

**Comment by shuizhongxiong** [comment]
> 你可以在picker里面content自己用 a:if 的

我自己 a:If 没用，因为组件外层用的还是 a:if，现在的问题是 a:if 里如果有很多 view 的时候，状态切换页面会卡住，该用 a:show 才可以。

**Comment by wyj580231** [comment]
#495
