### ISSUE TITLE
Stepper 步进器

### ISSUE THREAD

**Issue by hanf1990** [ant-design/ant-design-mini#269]
Stepper 步进器 输入值，onchange事件不触发，获取不到输入的值

**Comment by hanf1990** [comment]
什么时候能解决这个问题来？

**Comment by Alpsli** [comment]
步进器输入值会在在真机上点击键盘 onConfirm 时触发

**Comment by hanf1990** [comment]
> 步进器输入值会在在真机上点击键盘 onConfirm 时触发

不点击键盘呢？就是时时获取用户输入的值

**Comment by jc9702507** [comment]
需要添加onInput

**Comment by jc9702507** [comment]
用户输入的不是数字也需要得到？

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305
