### ISSUE TITLE
小程序form表单demo复制运行报错

### ISSUE THREAD

**Issue by TusiziLy** [ant-design/ant-design-mini#270]
## 组件

Form
## 基础库版本
0.0.22

- [ ] 1.x
- [ ] 2.x

## 手机系统

MacOs

## 组件库版本 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/31894246/191233709-91189407-6e4f-41cd-a691-7540eecbb5fa.png">

0.0.22
## 复现步骤 

1. 
2.

**Comment by Alpsli** [comment]
Form 组件重构中...

**Comment by jc9702507** [comment]
#305
