### ISSUE TITLE
Form表单设置字段值触发表单校验

### ISSUE THREAD

**Issue by T-yang857** [ant-design/ant-design-mini#272]
选择框的值一发生改变就清空其他的form-item的值，调用方法setFieldsValue方法进行重置之后会,如果传的有空值就会触发必填项的表单验证

**Comment by Alpsli** [comment]
form正在重构中...

**Comment by T-yang857** [comment]
预计啥时候能搞完呀。疫情常态化期间太多信息收集

**Comment by jc9702507** [comment]
#305
使用 1.0 表单组件
