### ISSUE TITLE
BladeView在钉钉小程序上报错

### ISSUE THREAD

**Issue by lili574** [ant-design/ant-design-mini#276]
## 组件

BladeView
## 基础库版本

1.25.7

## 手机系统

- [ ] iOS

## APP 

钉钉内部应用
## 组件库版本 

0.0.22
## 问题
https://github.com/ant-design/ant-design-mini/blob/3bb669414b781c35cc5d63513613ea894856501a/src/BladeView/index.ts#L48
在钉钉中exec返回的res项好像没有id和dataset属性，目前通过手动赋值解决了

**Comment by kava-hchaojie** [comment]
> 目前通过手动赋值解决了

如何手动赋值？ `<my-component id="xxx" />` 这样子吗？

**Comment by lili574** [comment]
修改了bladeView.js，这样：
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/45232618/194747313-f3e0d85e-34f1-40c2-bf1c-c090db9b6c47.png">

**Comment by kava-hchaojie** [comment]
> 修改了bladeView.js，这样： <img alt="image" width="1239" src="https://user-images.githubusercontent.com/45232618/194747313-f3e0d85e-34f1-40c2-bf1c-c090db9b6c47.png">

直接改源码啊？厉害。谢谢回复
