### ISSUE TITLE
NoticeBar在iPhone 14机型被遮挡

### ISSUE THREAD

**Issue by Mz1006** [ant-design/ant-design-mini#277]
## 组件

`<NoticeBar />`

## 基础库版本

- [ ] 2.x

## 设备机型
iPhone 14 

## 手机系统

- [ ] iOS

## 组件库版本 

Ant Design Mini 0.0.22

## 预期行为 

NoticeBar 文字不被遮挡，文字滚动正常

## 复现步骤 

 iPhone 14机型，NoticeBar 组件被顶部topbar遮挡二分之一，其他iPhone 机型以及安卓机型正常

正常如下：
https://img.bajiezu.cn/mini/Azfb/13.jpg

异常如下：
https://img.bajiezu.cn/mini/Azfb/14.jpg

## 复现 demo
`<notice 
      showIcon="{{true}}" 
      enableMarquee="{{true}}"
      loop="{{true}}"
      onTap="noticeClose"
      mode="closeable">
     <view style="padding-left:10rpx">超长文字滚动超长文字滚动超长文字滚动超长文字滚动超长文字滚动</view>
    </notice>`

**Comment by jc9702507** [comment]
这个组件好像没有做定位的处理，看看是不是使用这个组件的问题，比如去掉这个组件，换成一个view看看是不是对的

**Comment by jc9702507** [comment]
下载最新的支付宝应该就可以了，这个不是antd-mini问题
