### ISSUE TITLE
Filter组件在钉钉小程序里面无法使用，显示错误：worker render components is not sync

### ISSUE THREAD

**Issue by kava-hchaojie** [ant-design/ant-design-mini#278]
运行环境：钉钉小程序，开发工具版本：3.1.3，已开启component2编译，dingtalk/SDKVersion: 1.25.7  (钉钉V2引擎)
运行Filter官方文档里面代码，组件不能正常显示，控制台报错：

worker render components is not sync! can not find id from path: 1-1-3:/node_modules/antd-mini/es/Filter/FilterItem/index
Please check your axml: 
    in /node_modules/antd-mini/es/Filter/FilterItem/index
    in view
    in view
    in /node_modules/antd-mini/es/Filter/index
    in view
    in pages/ipqc/ipqc-form/ipqc-form

## 组件

filter, filter-item

## 基础库版本

- [ ] 1.x
- [ ] 2.x
dingtalk/SDKVersion: 1.25.7  (钉钉V2引擎)

## 设备机型
小程序开发工具模拟器：Version 3.1.3

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS
Android

## APP 

钉钉小程序

## 组件库版本 

v0.0.22

## 预期行为 

Filter正常展示

## 复现 demo

使用的是官方文档里面的代码：
https://mini.ant.design/components/filter

**Comment by jiangslee** [comment]
https://github.com/ant-design/ant-design-mini/issues/266#issuecomment-1262185665

参考下我这个setData的方法？

**Comment by kava-hchaojie** [comment]
> 参考下我这个setData的方法？
看了一下，我没有调用setData方法，完全是把官方的代码例子拷下来也跑不动。我都怀疑蚂蚁的这帮兄弟有没有在钉钉上面测过。

**Comment by Alpsli** [comment]
部分组件的确在钉钉小程序上有兼容问题，因为蚂蚁这边已经全部升级到appx2.0了，对于appx1.x的我们也只能够尽量兼容

**Comment by jiangslee** [comment]
> 部分组件的确在钉钉小程序上有兼容问题，因为蚂蚁这边已经全部升级到appx2.0了，对于appx1.x的我们也只能够尽量兼容

看来还是直接撸h5比较香

**Comment by jc9702507** [comment]
这个组件去掉了，使用 https://ant-design-mini.antgroup.com/components/selector#%E4%BD%BF%E7%94%A8selector%E8%87%AA%E5%AE%9A%E4%B9%89filter

**Comment by jc9702507** [comment]
#305
