### ISSUE TITLE
picker选择器，用在FormItem中时，设置必选无法检测

### ISSUE THREAD

**Issue by 56600535** [ant-design/ant-design-mini#288]
## 组件
Picker

## 基础库版本
2.7.12

## 设备机型
开发者工具

## 组件库版本 
最新版

## 复现步骤 
1. 选择picker对应的值
2. 点击提交出现如下情况
![image](https://user-images.githubusercontent.com/49943200/195817847-bc837e94-4a37-44e3-9e5b-9cb1f3d856ce.png)

## 复现 demo
axml代码
```
<view class="buy-content">
  <form form="{{form}}" initialValues="{{initialValues}}" onFinish="handleSubmit">
    <form-item label="产品类型" name="productType" required form="{{form}}">
      <picker onOk="pickerConfirm" placeholder="请选择" value="{{productType1}}"
        title="请选择" data="{{productTypeList}}">
      </picker>
      <!-- <view class="hidden-class">
        <input-item mode="form" value="{{productType}}" placeholder="请输入金额" maxLength="11" type="digit" hidden />
      </view> -->
    </form-item>
    <button slot="footer" type="primary" mode="form" form="{{form}}" htmlType="submit">提交
    </button>
  </form>
</view>
```
选中picker后，点击提交会提示“请输入必填项”

**Comment by 56600535** [comment]
有没有人呀，这个是bug还是代码错误呀

**Comment by kuromi-yl** [comment]
尝试下在picker中加mode="form" 呢，详细请见https://mini.ant.design/components/form

**Comment by 56600535** [comment]
> 尝试下在picker中加mode="form" 呢，详细请见https://mini.ant.design/components/form

我尝试了，不行。输入框可以，但是picker不行，而且我看到文档 picker也没有 mode 属性

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305
