### ISSUE TITLE
Collapse组件导致页面出现x滚动条

### ISSUE THREAD

**Issue by lili574** [ant-design/ant-design-mini#292]
## 组件

Collapse在宽度不为100vw的时候会导致页面出现x滚动条
模拟器上不会，真机上可以复现
## 基础库版本

dd 1.25.7
## 手机系统

- [x] iOS
- [x] Android
- [ ] HarmonyOS

## APP 
钉钉

## 组件库版本 
0.0.22

**Comment by lili574** [comment]
目前修改了`.collapse-line`的样式后可以了

**Comment by jc9702507** [comment]
@lili574 修改为100vw就没问这个问题？

**Comment by lili574** [comment]
> @lili574 修改为100vw就没问这个问题？
[](https://github.com/ant-design/ant-design-mini/blob/master/src/Collapse/CollapseItem/index.less#L121)
`width -> max-width`就没这个问题了

**Comment by lili574** [comment]
@jc9702507 

[https://github.com/ant-design/ant-design-mini/blob/master/src/Collapse/CollapseItem/index.less#L121](url)

`width -> max-width` 就没这个问题了

**Comment by jc9702507** [comment]
#305
