### ISSUE TITLE
Tab组件，点击当前active的tab，不触发onChange事件

### ISSUE THREAD

**Issue by hanf1990** [ant-design/ant-design-mini#294]
## 背景
 
点击当前active的tab，onChange事件不触发

## 期望
 

希望触发
![20221020162431](https://user-images.githubusercontent.com/37656336/196896506-bfa76cc1-0644-407e-b3b1-82678d0476a9.jpg)

**Comment by jc9702507** [comment]
对比 antd，onChange应该只是修改的才会调用。要是想加上点击event，可使用slot
```html
<view slot="title" slot-scope="tabs" onTap="handleTap" data-id="{{tabs.tab.id}}">
    {{tabs.tab.title}}
  </view>
```

**Comment by jc9702507** [comment]
#305 
使用 1.0 有说明自定义 https://ant-design-mini.antgroup.com/components/tabs#onchange%E5%8F%AA%E6%9C%89%E4%BF%AE%E6%94%B9%E6%89%8D%E8%83%BD%E5%87%BA%E5%8F%91%E6%83%B3%E8%A6%81%E5%9C%A8%E8%A7%A6%E5%8F%91current%E6%A0%87%E7%AD%BE%E7%9A%84%E7%82%B9%E5%87%BB%E9%9C%80%E8%A6%81%E6%80%8E%E4%B9%88%E5%81%9A
