### ISSUE TITLE
picker组件根据条件动态加载之后不弹窗

### ISSUE THREAD

**Issue by bzd-1** [ant-design/ant-design-mini#298]
## 组件

picker
## 基础库版本

- [ ] 1.x
- [ √] 2.x

## 设备机型
编辑器，真机模拟

## 手机系统

- [ ] iOS
- [√ ] Android
- [ ] HarmonyOS

## APP 

支付宝小程序

## 组件库版本 

0.0.22

## 预期行为 

使用a:if动态切换组件之后应该正常显示，但是实际并不会，奇怪的地方在于根据按钮事件触发的时候可以正常，显示，但是根据picker切换，修改条件之后，就不会再弹出来了

## 复现步骤 

1. 使用三个picker组件，第一个picker进行切换，用来确定第二个和第三个picker的展示
2. 再来一个按钮事件，也可以用来确定第二个和第三个picke的展示，
3. 通过picker切换时，后面两个picker就会把弹窗，但是通过按钮的就可以
![image](https://user-images.githubusercontent.com/68361950/197437305-091f7787-86ca-41ba-b0c4-ba0bf86c54f3.png)
![image](https://user-images.githubusercontent.com/68361950/197437463-f5c771df-afba-4035-ab19-a7ee353f7cf7.png)
![image](https://user-images.githubusercontent.com/68361950/197437497-44dad709-2a46-4d39-b6a4-8486825617fd.png)

**Comment by bzd-1** [comment]
感觉和form表单有关联，应为通过picker切换状态之后，再把条件作用到输入框的表单项时，表单项也会丢失掉，点击提交按钮时获取到的输入框字段是空

> ## 组件
> picker
> 
> ## 基础库版本
> * [ ]  1.x
> * [ √] 2.x
> 
> ## 设备机型
> 编辑器，真机模拟
> 
> ## 手机系统
> * [ ]  iOS
> * [√ ] Android
> * [ ]  HarmonyOS
> 
> ## APP
> 支付宝小程序
> 
> ## 组件库版本
> 0.0.22
> 
> ## 预期行为
> 使用a:if动态切换组件之后应该正常显示，但是实际并不会，奇怪的地方在于根据按钮事件触发的时候可以正常，显示，但是根据picker切换，修改条件之后，就不会再弹出来了
> 
> ## 复现步骤
> 1. 使用三个picker组件，第一个picker进行切换，用来确定第二个和第三个picker的展示
> 2. 再来一个按钮事件，也可以用来确定第二个和第三个picke的展示，
> 3. 通过picker切换时，后面两个picker就会把弹窗，但是通过按钮的就可以
>    ![image](https://user-images.githubusercontent.com/68361950/197437305-091f7787-86ca-41ba-b0c4-ba0bf86c54f3.png)
>    ![image](https://user-images.githubusercontent.com/68361950/197437463-f5c771df-afba-4035-ab19-a7ee353f7cf7.png)
>    ![image](https://user-images.githubusercontent.com/68361950/197437497-44dad709-2a46-4d39-b6a4-8486825617fd.png)
> 
> ## 复现 demo

感觉和form表单有关联，应为通过picker切换状态之后，再把条件作用到输入框的表单项时，表单项也会丢失掉，点击提交按钮时获取到的输入框字段是空

**Comment by wyj580231** [comment]
#305  可使用1.0
