### ISSUE TITLE
CheckBox 在部分安卓机型上，圆变成了椭圆

### ISSUE THREAD

**Issue by hq5544** [ant-design/ant-design-mini#306]
## 组件

CheckBox

## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [x] Android
- [ ] HarmonyOS

## APP 

支付宝

## 组件库版本 

1.0.25

## 预期行为 

圆形

## 复现步骤 

1. 直接在安卓客户端内使用，就是椭圆
2. iOS 正常

## 复现 demo

![image](https://user-images.githubusercontent.com/10363393/197999548-1d5496d6-b18f-4261-8d94-ecb1549040cc.png)

**Comment by jc9702507** [comment]
使用的是antd-mini还是antd-mini-rpx?另外提供下用的是什么手机

**Comment by hq5544** [comment]
> 使用的是antd-mini还是antd-mini-rpx?另外提供下用的是什么手机

组件是：@alipay/antd-mini/es/Checkbox/index
手机型号很多：iPhone X，魅族16t，小米8，vivo X9Plu，OPPO A8，Find X3，OPPO Reno6 pro，华为 P30 Pro，VIVO IQOO 8，荣耀 50，一加 9 RT，HONOR 60，HUAWEI STK-AL00

**Comment by jc9702507** [comment]
测试checkbox是可以的，是否有去修改antd-mini的css导致的。要是线上的小程序可提供下，也可在antd-mini群里沟通发下对应小程序

**Comment by hq5544** [comment]
> 测试checkbox是可以的，是否有去修改antd-mini的css导致的。要是线上的小程序可提供下，也可在antd-mini群里沟通发下对应小程序

alipays://platformapi/startapp?appId=2021001151636163&nbupdate=syncforce&page=subpkg%2Fpages%2Fenterprise-certify%2Findex
可以访问这个，上述机型底部的 CheckBox 会变形。没有修改 antd-mini 的 css。

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305

**Comment by jc9702507** [comment]
这个问题好像是由于右侧宽度太大就可能那样，需要修改

**Comment by jc9702507** [comment]
https://ant-design-mini.antgroup.com/components/checkbox
