### ISSUE TITLE
form 中使用picker问题，如果data的数据通过远程获取并setData后，form表单所有验证失效问题

### ISSUE THREAD

**Issue by xufeng1026** [ant-design/ant-design-mini#327]
你好，我在form中使用picker ,但我的picker 的data数据源来自远程服务器中，在page的onshow钩子函数中远程获取数据。并通过setData设置picker的data数据，数据能够设置成功，并能界面也正常显示，但form中的所有控件验证都失效，这是什么原因？

**Comment by xufeng1026** [comment]
有没有微信或者qq群问题讨论群？

**Comment by Alpsli** [comment]
我们正在对form进行全面重构，1.0版本预发下个月会发布

**Comment by jc9702507** [comment]
https://github.com/ant-design/ant-design-mini/issues/305

**Comment by jc9702507** [comment]
使用1.0没这个问题
