### ISSUE TITLE
blade-view组件在钉钉小程序,点击 滑动时无反应并报错!

### ISSUE THREAD

**Issue by mozhewuyan** [ant-design/ant-design-mini#334]
## 组件

- [x] blade-view
## 基础库版本

- [x] 1.25.14

## 设备机型
- [x] iOS
## 手机系统

- [x] iOS

## 预期行为 
点击侧边字母应跳转对应区域,及滚动至对应区域 侧边字母样式改变

## 复现步骤 

1. 
2.

**Comment by mozhewuyan** [comment]
![Snipaste_2022-11-14_13-44-17](https://user-images.githubusercontent.com/93707816/201585100-3aeef776-fff9-407c-ab18-94b7a861bc09.png)
![Snipaste_2022-11-14_13-44-10](https://user-images.githubusercontent.com/93707816/201585106-a77b53c5-5c4c-4046-adda-6e8be6679a5f.png)

**Comment by jc9702507** [comment]
https://mini.ant.design/components/index-bar

**Comment by jc9702507** [comment]
#305 
1.0没这个问题
