### ISSUE TITLE
elevator组件title插槽传值错误

### ISSUE THREAD

**Issue by malaxlx** [ant-design/ant-design-mini#370]
## 组件

<elevator></elevator>

## 基础库版本

- [x] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 组件库版本 

0.0.25

## 预期行为 

![image](https://user-images.githubusercontent.com/45837333/203718245-b4e7131a-a2e1-4be8-a4dc-c37a1611ffd1.png)

此处active应为active="{{activeIndex===props.index}}"
原方法会导致组件solt取到active的值永远为false

## 复现步骤 

1. 
2.

**Comment by jc9702507** [comment]
这个组件重构了，可等下1.0 alpha发布使用

**Comment by jc9702507** [comment]
#305 使用1.0 tabs
