### ISSUE TITLE
tabs标签页电梯组件模式功能待完善

### ISSUE THREAD

**Issue by linhongpeng7** [ant-design/ant-design-mini#396]
## 背景
 
无徽标功能，切换无上下滑动功能

## 期望
 电梯组件模式添加徽标设置功能，切换tab的时候添加上下滑动功能

**Comment by Alpsli** [comment]
理解有两个点：一个是希望 tabs 新增徽标，另外一个是电梯模式点击 tab 让页面滚动 smooth ?

**Comment by linhongpeng7** [comment]
> 理解有两个点：一个是希望 tabs 新增徽标，另外一个是电梯模式点击 tab 让页面滚动 smooth ?
嗯嗯对的，可以尽快修复吗

**Comment by Alpsli** [comment]
这块能力我们正在重构，将在 1.0 版本更新上线

**Comment by linhongpeng7** [comment]
> 这块能力我们正在重构，将在 1.0 版本更新上线

好的感谢，麻烦问下上线时间预计是什么时候

**Comment by Alpsli** [comment]
alpha版本下周，正式版本可能需要打磨一段时间

**Comment by linhongpeng7** [comment]
好的了解了

**Comment by jc9702507** [comment]
tabs会跟content的解耦，1.0的tabs会在示例里有这个

**Comment by wyj580231** [comment]
#305
