### ISSUE TITLE
pick组件 无法清空value之前的值

### ISSUE THREAD

**Issue by longdan-qilin** [ant-design/ant-design-mini#403]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2.

**Comment by longdan-qilin** [comment]
![lQLPJx9c3hb-8xzMmc0BbbDN7GdZcIZyVAOJ60VIQAMA_365_153](https://user-images.githubusercontent.com/67103351/205582477-e3f21c08-6788-4987-9338-3be54b19b306.png)

**Comment by flameOvO** [comment]
看下来是有bug，给个临时方案可以通过自定义onFormat解决
```
  onFormat(value, column) {
    if (column instanceof Array) {
      return column.filter(c  => c !== undefined).map(function (c) {
        if (typeof  c === 'object') {
          return c.label
        }
        return c
      }).join('-');
    }
    return column && column.label || column || '';
  },
```

**Comment by jc9702507** [comment]
#305
