### ISSUE TITLE
Filter 筛选卡支持自定义 Item

### ISSUE THREAD

**Issue by szh0001** [ant-design/ant-design-mini#434]
## 背景
 

不想用默认的selector组件，能简单切换到 checklist吗
## 期望
 
能自定义Item 组件

**Comment by jc9702507** [comment]
Filter组件会去掉，要是需要用这个组件可使用selector + 自定义下拉列表；
想用checklist其实是 checklist + 自定义下拉列表；
自定义下拉列表会在1.0之后提供

**Comment by jc9702507** [comment]
#305
