### ISSUE TITLE
在钉钉小程序中使用tabs swipeable实现滑动切换tab不生效

### ISSUE THREAD

**Issue by ctf769** [ant-design/ant-design-mini#455]
## 组件

tabs
## 基础库版本
antd 4.20.7

- [x] 1.x
- [ ] 2.x

## 设备机型
ios13
## 手机系统

- [1 ] iOS
- [ ] Android
- [ ] HarmonyOS

## 组件库版本 

0.0.19
## 复现步骤 

1. 
2.

**Comment by wyj580231** [comment]
tabs会跟swiper解藕，参照 https://mini.ant.design/components/tabs#swiper

**Comment by jc9702507** [comment]
#305

**Comment by jc9702507** [comment]
使用1.0 tabs
