### ISSUE TITLE
search-bar  input事件失效

### ISSUE THREAD

**Issue by longdan-qilin** [ant-design/ant-design-mini#468]
![image](https://user-images.githubusercontent.com/67103351/209263198-583661cf-a5ca-4d0b-85ca-86302e25311e.png)
打印出来没值

**Comment by jc9702507** [comment]
这个组件会去掉，可试试使用 https://ant-design-mini.antgroup.com/components/input#searchbar-%E6%90%9C%E7%B4%A2%E6%A1%86

**Comment by jc9702507** [comment]
#305
