### ISSUE TITLE
SwipeAction组件使用onGetRef控制按钮显隐时只对列表最后一项生效

### ISSUE THREAD

**Issue by ctf769** [ant-design/ant-design-mini#484]
## 组件

swipe-action
## 基础库版本
antd-mini@0.0.19

- [ ] 1.x
- [x] 2.x

## 设备机型
ios-13
## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS

## 组件库版本 

antd-mini@0.0.19
## 预期行为 

预期使用onGetRef中的reset(0)方法可以关闭列表任意项的按钮区域展开
## 复现步骤 

1. 在官方文档 【https://mini.ant.design/components/swipe-action】所给的 组件实例方法对应代码中
2. 将只有一项【list-item】改成有多项【list-item】
3. 会发现当我们点击 【点击取消】按钮，只对list最后一项有效果
## 复现 demo

`
<tabs
  index="{{curIdx}}"
  type="{{type}}"
  fallback="{{true}}"
  sticky="{{sticky}}"
  onChange="changeTab"
>
  <block a:for="{{tabs}}">
    <tab-content tab="{{item}}">
      <swipe-action data-index="{{index}}" right="{{[{
        type: 'default',
        text: '新增一个',
      }, {
        type: 'primary',
        text: '取消收藏',
      }, {
        type: 'danger',
        text: '删除',
      }]}}" onRightButtonTap="onSingleRightItemClickDelete" onGetRef="getRef">
        <list-item arrow="right" data-index="{{index}}" onTap="onItemClick">
          组件实例方法
        </list-item>
      </swipe-action>
    </tab-content>
  </block>
  <button onTap="resetPosition">
    点击取消
  </button>
</tabs>
`

**Comment by jc9702507** [comment]
可使用 1.0 https://mini.ant.design/components/swipe-action/
