### ISSUE TITLE
button  不支持获取支付宝小程序获取手机号码

### ISSUE THREAD

**Issue by chuxin520** [ant-design/ant-design-mini#492]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [x] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2.

**Comment by chuxin520** [comment]
button 不支持获取支付宝小程序获取手机号码

**Comment by jc9702507** [comment]
能否发下你使用的代码，是使用scope？

**Comment by jc9702507** [comment]
这个是button组件有的props没加上，需要修改

**Comment by jc9702507** [comment]
fixed

**Comment by jc9702507** [comment]
#305
