### ISSUE TITLE
组件预览器本身不应该出现垂直滚动条

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mini#493]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/210544749-00e5fae2-e9ab-41e3-a72e-9c285db7fd12.png">

https://mini.ant.design/components/index-bar/

**Comment by wujunwen1997** [comment]
我来瞧一瞧

**Comment by wujunwen1997** [comment]
> <img alt="图片" width="1792" src="https://user-images.githubusercontent.com/507615/210544749-00e5fae2-e9ab-41e3-a72e-9c285db7fd12.png">
> 
> https://mini.ant.design/components/index-bar/

你的是什么浏览器？

**Comment by wujunwen1997** [comment]
> <img alt="图片" width="1792" src="https://user-images.githubusercontent.com/507615/210544749-00e5fae2-e9ab-41e3-a72e-9c285db7fd12.png">
> 
> https://mini.ant.design/components/index-bar/

模拟器外层的那个滚动条，你看每个组件应该都有，是个浏览器的兼容问题，这个我让框架看看
indexbar 组件本身有用到scroll-view 组件，它会带一个滚动条，这个我提个pr改一下

**Comment by afc163** [comment]
PR 在哪？

**Comment by afc163** [comment]
找到了 https://github.com/ant-design/ant-design-mini/pull/503

**Comment by jc9702507** [comment]
这个还需要模拟器修改
