### ISSUE TITLE
Picker 选择器 BUG！显示有问题

### ISSUE THREAD

**Issue by zhanghen1234** [ant-design/ant-design-mini#500]
[](![i[](mage](https://user-images.githubusercontent.com/39692530/210960841-c64259d1-4cbf-4047-9efa-96077385b976.png))
)

**Comment by zhanghen1234** [comment]
![image](https://user-images.githubusercontent.com/39692530/210961681-f9c136c9-62c2-45b2-b0ac-451792183fa7.png)

**Comment by wyj580231** [comment]
#499
