### ISSUE TITLE
希望增加Sticky吸顶容器组件

### ISSUE THREAD

**Issue by deajax** [ant-design/ant-design-mini#564]
## 背景
 
没有吸顶容器组件，无法做到某些效果

## 期望
 
希望添加Sticky 吸顶容器组件

## 思路
 
如下示例：
https://tdesign.tencent.com/miniprogram/components/sticky
https://vant-contrib.gitee.io/vant/#/zh-CN/sticky

**Comment by jc9702507** [comment]
这个用position: sticky是不是就可以呢，好像不需要组件
