### ISSUE TITLE
Form createForm 自定义组件 emit 报错

### ISSUE THREAD

**Issue by T-yang857** [ant-design/ant-design-mini#580]
使用官方的自定义表单项demo代码，在模拟器中调试报错，demo : form-location
![image](https://user-images.githubusercontent.com/32295161/218660947-569a4b9a-ecc3-45ad-a327-62984d2b19b7.png)

**Comment by jc9702507** [comment]
需要发下怎么使用的，是否是示例相同

**Comment by jc9702507** [comment]
测试是可以的，是否有加上component2: true

**Comment by jc9702507** [comment]
要是使用ts，修改为 "typescript": {
      "transpileOnly": true
    },
比如：
mini.project.json
```json
{
  "format": 2,
  "compileOptions": {
    "typescript": {
      "transpileOnly": true
    },
    "less": true,
    "component2": true,
    "enableNodeModuleBabelTransform": true
  }
}
```
