### ISSUE TITLE
step修改current状态

### ISSUE THREAD

**Issue by linanruohan** [ant-design/ant-design-mini#585]
横纵步骤条修改current为空心蓝
蓝色：完成了的，空心蓝：current，灰色：还没进行的

**Comment by jc9702507** [comment]
![image](https://user-images.githubusercontent.com/113670357/220038418-2c25bb20-f367-48f3-814d-e3918c835d8f.png)
做这样的改进：current稍微修改下让看起来更明显，其他不变
