### ISSUE TITLE
有支持从一个区域拖到另外一个区域的组件吗

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-mini#59]
## 背景
比如我想选中某个功能块拖到另外一个区域加入。这样的场景

## 期望
有支持从一个区域拖到另外一个区域的组件吗

**Comment by Alpsli** [comment]
> ## 背景
> 比如我想选中某个功能块拖到另外一个区域加入。这样的场景
> 
> ## 期望
> 有支持从一个区域拖到另外一个区域的组件吗
> 
> ## 思路

你的具体场景是什么呢？Antd-design-mini 暂时没有这样的组件，而且我觉得这种组件不会放到 UI 组件资产库中

**Comment by fangqibin** [comment]
> > ## 背景
> > 比如我想选中某个功能块拖到另外一个区域加入。这样的场景
> > ## 期望
> > 有支持从一个区域拖到另外一个区域的组件吗
> > ## 思路
> 
> 你的具体场景是什么呢？Antd-design-mini 暂时没有这样的组件，而且我觉得这种组件不会放到 UI 组件资产库中

就是正常手机拖拽，比如移动顺序啥的

**Comment by miaodongqing** [comment]
没有计划支持
