### ISSUE TITLE
form-switch未将disabled属性封装进去，导致设置disabled

### ISSUE THREAD

**Issue by Raina-mtn** [ant-design/ant-design-mini#590]
## 组件

form-switch
## 基础库版本

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
![Snipaste_2023-02-20_11-10-07](https://user-images.githubusercontent.com/100856995/220000875-7fb329b8-3d76-4c9f-be86-5dc274cb9561.png)

2.

**Comment by Raina-mtn** [comment]
导致disabled不生效

**Comment by jc9702507** [comment]
fixed
