### ISSUE TITLE
使用indexBar控制台会报错误

### ISSUE THREAD

**Issue by Raina-mtn** [ant-design/ant-design-mini#598]
## 组件

indexBar
## 基础库版本

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
![image](https://user-images.githubusercontent.com/100856995/220523604-3e5274d2-9979-4ed1-a663-907f2a17d657.png)

2.

**Comment by jc9702507** [comment]
是示例还是修改过什么

**Comment by wujunwen1997** [comment]
![image](https://user-images.githubusercontent.com/30853720/220538928-59486548-93e2-4a78-99f1-04cbb7259570.png)

**Comment by Raina-mtn** [comment]
找到问题了是indexbar这个组件中id选择器少写了个#，已经在群里回复过了
![image](https://user-images.githubusercontent.com/100856995/220823106-3316134a-c048-4f20-8219-8fa98a5b4afb.png)

**Comment by jc9702507** [comment]
fixed
