### ISSUE TITLE
希望form可以增加getFieldsValue，用于获取当前填写过的所有表单信息

### ISSUE THREAD

**Issue by Raina-mtn** [ant-design/ant-design-mini#609]
## 背景
 
暂存表单的时候，需要拿到当前填写过的信息用于暂存，但是不需要校验

## 期望
 
可以增加getFieldsValue，用于获取当前填写过的所有表单信息

## 思路
 
循环所有field拿到所有值

**Comment by jc9702507** [comment]
看起来是需要的
