### ISSUE TITLE
form表单组件在「三星折叠屏 SM-F907N」上@ 符号后无法输入，内容会被自动清空，使用该手机访问官网示例后仍复现。（例如：“123@”后输入“1”，内容就被清空了）系统号：Android 10；支付宝版本号：10.3.50；

### ISSUE THREAD

**Issue by guoyuexu** [ant-design/ant-design-mini#621]
## 组件

form表单组件

## 设备机型
三星折叠屏 SM-F907N
## 手机系统
Android 10

## APP 
支付宝

## 组件库版本 

1.2.1，在官网示例文档仍能复现。

## 预期行为 

输入@符号后，可正常输入一切内容，不会清空原内容。
## 复现步骤 

1. 直接使用该机型访问官网demo小程序
2. 输入数字后加上@符号，再随便输入任意字符，内容都会被清空

**Comment by wyj580231** [comment]
经测试是[原生input](https://opendocs.alipay.com/mini/component/input )的问题，可以设置\<form-input enableNative="{{false}}" /\>来解决
