### ISSUE TITLE
Form支持批量设置表单值

### ISSUE THREAD

**Issue by yuruwang** [ant-design/ant-design-mini#628]
## 背景
 
目前表单设置字段值只能用setFieldValue一个一个设置，虽然setInitialValues可以批量设置初始值，但是setInitialValues不能触发onValueChange的监听。

## 期望
 
Form提供一个api支持批量设置表单值，类似antd表单

**Comment by jc9702507** [comment]
这里好像用setFieldValue就可以。不过提供setFieldsValue应该可以更方便。

**Comment by yuruwang** [comment]
> 这里好像用setFieldValue就可以。不过提供setFieldsValue应该可以更方便。

是的，setFieldValue可以用，但是字段比较多的时候，设置起来很繁琐 @jc9702507

**Comment by jc9702507** [comment]
嗯，这个还是需要比较方便

**Comment by jc9702507** [comment]
可以使用了
