### ISSUE TITLE
Popup蒙层出现 蒙层后的页面能滚动

### ISSUE THREAD

**Issue by Hanjinhong0304** [ant-design/ant-design-mini#635]
1、antd-mini版本 ^1.2.1
2、真机 手机iphone 11，系统16.3
3、模拟机上也可以浮现 iphone8 plus 系统 14.4
4、情况是下拉的时候 后面的页面就进行下拉了

**Comment by jc9702507** [comment]
popup问题只看真机，IDE里是有问题

**Comment by Hanjinhong0304** [comment]
> 



> popup问题只看真机，IDE里是有问题

我有在真机中看的 iphone11 下载的内测包看的

**Comment by Hanjinhong0304** [comment]
问题的原因是没有用scroll-view

**Comment by zhoujingchao** [comment]
> 问题的原因是没有用scroll-view

确定么？我这边一直不行，并且用 catchTouchMove，也不行， 伪代码结构如下

<view>首页可滚动内容</view>

<popup>
首页弹出层底部弹出固定高度
<scroll-view scroll-y catchTouchMove>
1、内容很多就会滚，但并不会穿透到首页滚动
**2、内容少，达不到滑动，但滑动此区域就会穿透到首页滚动了**
</scroll-view>
</popup>

备注：
1、我还尝试在popup或scroll-view外层再包一个view，使用catchTouchMove或者disable-scroll都不行

**Comment by zhoujingchao** [comment]
> 问题的原因是没有用scroll-view

确定么？我这边一直不行，并且用 catchTouchMove，也不行， 伪代码结构如下

```
<view>首页可滚动内容</view>
<popup>
  <scroll-view>
    首页弹出层底部弹出固定高度
    1、内容很多就会滚，但并不会穿透到首页滚动
    2、内容少，达不到滑动，但滑动此区域就会穿透到首页滚动了
  </scroll-view>
</popup>
```

备注：
1、我尝试了popup或scroll-view外层再包一个view，使用catchTouchMove或者disable-scroll都不行
2、还尝试了浮层的visible显示状态来对应首页的view来控制disable-scroll也不行

**Comment by wyj580231** [comment]
> > 问题的原因是没有用scroll-view
> 
> 确定么？我这边一直不行，并且用 catchTouchMove，也不行， 伪代码结构如下
> 
> ```
> <view>首页可滚动内容</view>
> <popup>
>   <scroll-view>
>     首页弹出层底部弹出固定高度
>     1、内容很多就会滚，但并不会穿透到首页滚动
>     2、内容少，达不到滑动，但滑动此区域就会穿透到首页滚动了
>   </scroll-view>
> </popup>
> ```
> 
> 备注： 1、我尝试了popup或scroll-view外层再包一个view，使用catchTouchMove或者disable-scroll都不行 2、还尝试了浮层的visible显示状态来对应首页的view来控制disable-scroll也不行

在scroll-view加上disable-lower-scroll="out-of-bounds" disable-upper-scroll="out-of-bounds"试试

**Comment by zhoujingchao** [comment]
@wyj580231 谢谢，可以解决👏👏

**Comment by laoxiaokang** [comment]
请问是不是基础库1.X的不支持disable-lower-scroll="out-of-bounds" disable-upper-scroll="out-of-bounds"这个配置

**Comment by wyj580231** [comment]
邮件已收到
