### ISSUE TITLE
Popup在钉钉小程序中开启动画，关闭时报错：worker render components is not sync

### ISSUE THREAD

**Issue by xieshiyi** [ant-design/ant-design-mini#637]
## 组件
Popup

## 基础库版本

1.25.7

- [x] 1.x
- [ ] 2.x

## 手机系统

- [x] iOS
- [x] Android
- [ ] HarmonyOS

## APP 
钉钉小程序

## 组件库版本 
0.0.25

## 预期行为 
打开和关闭弹窗都不会报错

## 复现步骤 
1. 打开弹窗
2. 关闭弹窗
3. 控制台报错

## 复现 demo
![image](https://user-images.githubusercontent.com/20486830/224641577-77cedf07-a723-4446-b535-614160935bff.png)

**Comment by jc9702507** [comment]
这个不维护的，推荐使用1.0。要是还需要使用可fork维护。
