### ISSUE TITLE
tab组件过长点击到最后一个不能知道接下来是否还有tab项目

### ISSUE THREAD

**Issue by ClinccGG** [ant-design/ant-design-mini#644]
## 背景
 
tab组件过长点击到最后一个不能知道接下来是否还有tab项目

## 期望
 
是否需要加上一个props，用来做滑动跟边距的距离，或者加个属性来同步下线版本的效果

## 思路
 
目前在向小程序dom上添加scroll-left尝试

**Comment by ClinccGG** [comment]
if (this.props.items && this.props.offsetLeft) {
      let setLeft = this.props.items.length > 3 ? 0.25 : 1 / this.props.items.length
      let scrollLeft = this.props.current * windowWidth * setLeft;
      if (this.props.current <= 2) {
        this.setData({
          scrollLeft: 0
        })
      } else {
        this.setData({
          scrollLeft: (this.props.current - 2) * windowWidth * setLeft
        })
      }
      return
    }
    if ((prevProps.items !== this.props.items || !this.isEqualValue(prevData)) && !this.props.offsetLeft) {
      this.updateScrollLeft();
    }

已解决

**Comment by jc9702507** [comment]
最新的加了 scrollMode属性，可使用 scrollMode="center"

**Comment by ClinccGG** [comment]
收到  谢谢
