### ISSUE TITLE
action-sheet在iOS端有闪现后再从下方跳出的问题

### ISSUE THREAD

**Issue by ffinly** [ant-design/ant-design-mini#653]
## 组件
action-sheet

## 基础库版本
dingtalk/SDKVersion: 1.25.7

## 设备机型
iPhone 13

## 手机系统
- iOS 16.3.1

## APP 
钉钉 7.0.10

## 组件库版本 
1.4.0

## 预期行为 
action-sheet 展开时，会先闪现一下展出后的action-sheet，再从下方跳出（IDE调试时没有这个闪现现象）

## 复现步骤 
1. 使用的是官方的示例代码

## 复现 demo
1. 使用的是官方的示例代码

**Comment by ffinly** [comment]
升级了最新版的IDE开发工具后，问题解决

**Comment by ffinly** [comment]
该问题还是继续存在，同时 modal 组件关闭的时候也会有闪现的问题

**Comment by jc9702507** [comment]
是真机有问题？

**Comment by ffinly** [comment]
对的，是真机有问题，但是是间歇性的（modal的场景是：会从侧边弹出，关掉的时候会有多个窄的白色长条闪现），有的时候上传的版本有问题，有的时候又很正常。但是我今天把 npm 包全部删掉，重新安装后，再上传，又正常了。
我也是刚接触前端和小程序开发，知道你们这个也主要是钉钉自带的 action-sheet 在pc上无法正常使用，同时自带的alert和confirm的对话框的在pc上体验太差，并且在安卓上面还有部分兼容问题。

但是使用了ant design mini后，兼容问题解决了。目前相比钉钉原生控件，我发现有几个可以改善的地方：
1. action sheet支持的项目数太少，目前我做了一个搜索并选择的功能，就是采用原生的 action sheet 来实现的，这样实现弹窗并选择，交互起来比较方便（但是在pc上使用，会强制打开钉钉窗口并在窗口正中央弹出，不会直接在小程序上，alert和confirm也是同理），选择后回填回界面，方便根据这个进行二次搜索和结果展示。我有尝试用你们这个的action sheet，发现支持的项目数量太少（钉钉原生的我试了一下，iphone实机上面 500左右钉钉程序是会直接崩掉，200速度还能接受，基本上秒出，到300就会慢不少，所以我现在是限定在200，这个数量在安卓、苹果、pc、mac上面都是显示得很正常，速度也比较快），不能滑动选择，如果能实现跟原生的 action sheet 一样（这个也是我目前没办法，必须使用的原生控件之一），这样功能就实用得多
2. modal关闭的时候，会先转成一个很窄的白色长条，这个动画能否优化一下，要么直接关掉（目前钉钉小程序的逻辑就是直接关掉），要么逐渐变小。现在这种方式，让人感觉有点突兀，动画效果不自然。同时modal显示文字的时候不支持换行（我试过了\n 和 \n\n 都不行，会转为一个空格），并且只能显示3行文字，如果多了就会溢出。这个窗体的大小能否根据文字自动调整下高度。

非常感谢你们开发出来的 ant design mini，在钉钉小程序原生生态这么差的情况下，也能够在使用上有较好的体验。我也有用 你们的ant design f2在钉钉小程序上展示图表（折线、多折线、柱状图、饼图），体验感觉还是非常不错的，就是官方文档太简单，有些问题需要看源码或者网上搜索解决。f6我也有简单尝试。希望你们能做出更多更好的开源产品出来。

**Comment by jc9702507** [comment]
这个应该是钉钉小程序里有的bug。在支付宝小程序里好像没这个问题。

**Comment by jc9702507** [comment]
1. action-sheet在钉钉真机IOS测试好像没有你说的闪一下再从底部弹出。是否可以提供一个视频；
2. ”action sheet支持的项目数太少“ 这个是什么意思呢？
3.  modal这个是否也可提供一个视频，钉钉真机IOS测试好像没什么问题

**Comment by jc9702507** [comment]
> modal里面实现换行的话，我要怎么弄呢

可试试：
```html
<view style="word-wrap: break-word;"></view>
```

**Comment by ffinly** [comment]
我尝试这两种方式都不行，都没显示，麻烦看下怎么样来添加呢：

`<modal
  title="{{modalTitle}}"
  content="{{modalContent}}"
  visible="{{modalVisible}}"
  onClose="handleModalClose"
  primaryButtonText="{{modalPrimaryButtonText}}"
  onPrimaryButtonTap="handlePrimaryButtonTap">
  <view class="body">
    <view style="word-wrap: break-word;"></view>
  </view>
</modal>`

`<modal
  title="{{modalTitle}}"
  content="{{modalContent}}"
  visible="{{modalVisible}}"
  onClose="handleModalClose"
  primaryButtonText="{{modalPrimaryButtonText}}"
  onPrimaryButtonTap="handlePrimaryButtonTap">
  <view style="word-wrap: break-word;"></view>
</modal>`

我看官方文档里面有个自定义样式的是这样的，但是没详细的说明：
`<modal 
  visible="{{customBodyVisible}}" 
  onClose="handleClose">
  <view class="body">
    <image mode="scaleToFill" src="https://mdn.alipayobjects.com/huamei_yujk1o/afts/img/A*xYjqRJiKsvoAAAAAAAAAAAAADuaJAQ/original" class="bodyImg"/>
    <view class="bodyAction"><icon type="CloseCircleOutline" onTap="handleClose"/></view>
  </view>
</modal>`

**Comment by jc9702507** [comment]
```html
<modal 
  visible="{{true}}"
>
  <view style="width:200px;word-wrap: break-word;background:#fff;">
    fewfewfewfewfewfwefewfewfewfewfwefewfewfewfewfewfew
  </view>
</modal>
```

**Comment by ffinly** [comment]
> ```
> <modal 
>   visible="{{true}}"
> >
>   <view style="width:200px;word-wrap:break-word;background:#fff;">
>     fewfewfewfewfewfwefewfewfewfewfwefewfewfewfewfewfew
>   </view>
> </modal>
> ```

谢谢，这个可以实现换行，我看源码，发现有个bodyStyle可以用，试了下面的方法：

```
<modal
  title="{{modalTitle}}"
  content="{{modalContent}}"
  visible="{{modalVisible}}"
  onClose="handleModalClose"
  bodyStyle="height: 80vh; overflow-y: auto; word-wrap: break-word; white-space: pre-line;" 
  primaryButtonText="{{modalPrimaryButtonText}}"
  onPrimaryButtonTap="handlePrimaryButtonTap">
</modal>
```

这样子完美的解决了换行及窗体内容溢出的问题，并且保留了文本原始的多个空格和换行符这些。
理论上 action-sheet 也可以用同样的方式来解决溢出的问题。

**Comment by ffinly** [comment]
action sheet 好像不行，官方文档里面有 style 属性，但是 源码中没有：
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/29793346/228587240-cf10afdb-b762-4fe6-a27d-44c90d4fdb20.png">

```
/**
 * @description 头像，可展示头像以及用户名等简要信息。
 */
export interface IActionSheetProps extends IBaseProps {
    /**
     * @description 标题
     * @default ""
     */
    title: string;
    /**
     * @description 面板选项列表
     * @default []
     */
    actions: IActionItem[];
    /**
     * @description 取消按钮文字
     * @default []
     */
    cancelText: string;
    /**
     * @description 是否显示
     * @default []
     */
    visible: string;
    /**
     * @description 点击选项时触发，禁用或加载状态下不会触发
     */
    onAction: (aciton: IActionItem, index: number, e: any) => void;
    /**
      * @description 关闭时触发
     */
    onClose: (e: any) => void;
}
export declare const ActionSheetDefaultProps: Partial<IActionSheetProps>;
```

**Comment by jc9702507** [comment]
这里讨论的问题，有的解决了，有的是另外的问题，可重新开对应的issue
