### ISSUE TITLE
Form表单支持设置errors和status

### ISSUE THREAD

**Issue by yuruwang** [ant-design/ant-design-mini#654]
## 背景
 
目前Form表单的api不支持主动设置表单error。现在有业务场景是后端接口返回表单项的错误状态和文案，需要前端主动设置到表单上。

## 期望
 
Form表单支持批量设置表单的errors&status

**Comment by jc9702507** [comment]
https://mini.ant.design/components/form#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9%E6%A0%A1%E9%AA%8C 这个可以自定义的

**Comment by jc9702507** [comment]
```html
<form-input
  label="用户名"
  name="account"
  required
  placeholder="请输入用户名"
  message="需要输入用户名"
  validateStatus="success"
  ref="handleRef"
>
  <view slot="footer" slot-scope="item">
    <!--这里都是你自定义的-->
    <view class="errors">
      <icon type="CloseCircleOutline" style="margin-right: 4px;" />
      {{item.errors}}
    </view>
  </view>
</form-input>
```

**Comment by jc9702507** [comment]
需要加上：
- setFieldValidatorStatus
- setFieldsValidatorStatus
- getFieldsValidatorStatus
