### ISSUE TITLE
CheckboxGroup 编译错误 variable.less内部依赖路径错误

### ISSUE THREAD

**Issue by wanglinglei** [ant-design/ant-design-mini#670]
## 组件

CheckboxGroup

## 组件库版本 

1.5.1

CheckboxGroup 编译错误 variable.less内部依赖 style/themes/index.less  路径错误

**Comment by jc9702507** [comment]
这个好像是不需要的。CheckboxGroup的index.less其实没有用到这个variable.less，编译也不会报错的
