### ISSUE TITLE
picker在高版本iOS，未选择也是黑色，没有置灰

### ISSUE THREAD

**Issue by wd1e23456** [ant-design/ant-design-mini#687]
## 组件
picker

## 基础库版本
2.8.5

## 设备机型
iPhoneX以上

## 手机系统
IOS

## APP 
支付宝

## 组件库版本 
^1.3.2

## 预期行为 
未选择智置灰

**Comment by jc9702507** [comment]
antd-mini 使用props解决这个问题。这个问题还是需要appx才能修改，antd-mini只能用props来不去掉更好的动画

**Comment by jc9702507** [comment]
使用最新的antd-mini，可使用props解决
