### ISSUE TITLE
form-item自定义组件在didMount中调用this.emit发送值无法绑定

### ISSUE THREAD

**Issue by smao999** [ant-design/ant-design-mini#688]
## 组件

form-item
## 基础库版本
- [ ] 1.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. form-item自定义组件绑定的值为name="value"
2. 在自组件组件的didMount里面调用this.emit('onChange', value),无法更改form-item里面绑定value变量

**Comment by jc9702507** [comment]
`this.emit('onChange', value)` 的意思表单值修改后去调用this.emit让form能得到表单修改了。在didMount里去调用this.emit('onChange', value)，但表单其实没有修改？

**Comment by jc9702507** [comment]
你的需求是什么呢，为什么要在didMount去调用`this.emit('onChange', value)`

**Comment by jc9702507** [comment]
组件didMount了但是外层页面还没有，this.emit就修改不了外层页面。

Options:
1. 在didMount里setTimeout this.emit
2. 不使用didMout，修改为pageEvents
```
pageEvents: {
    onReady() {
      this.emit()
    },
  },
```
