### ISSUE TITLE
form-item自定义组件内设置子组件为slider组件，无法绑定默认值，默认值从props里获取

### ISSUE THREAD

**Issue by smao999** [ant-design/ant-design-mini#689]
## 组件

form-item，slider
## 基础库版本

- [ ] 1.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. form-item包裹组件slider，slider组件defaultvalue值为父组件传递
2. 在didMount中setdata设置默认值，无法绑定

**Comment by jc9702507** [comment]
defaultValue是不能使用setData修改的，要是想要修改使用value
