### ISSUE TITLE
form-input表单组件的required属性由data控制，data更新了required并没有更新

### ISSUE THREAD

**Issue by yuruwang** [ant-design/ant-design-mini#692]
## 组件

form-input

## 基础库版本

- [ ] 2.x

## 设备机型

iphone13

## 手机系统

 iOS

## APP 
支付宝

## 组件库版本 

1.6.1

## 预期行为 

form-input表单组件的required属性由data控制，data更新后required的校验应该也要更新

## 复现步骤 

1. 
2.

**Comment by jc9702507** [comment]
测试好像没问题，需要发下js, axml

**Comment by jc9702507** [comment]
required更新后，对应的field会重写reset，校验、value都会更新

**Comment by jc9702507** [comment]
这个问题解决了？ @yuruwang
