### ISSUE TITLE
怎么自定义主题?  具体方法怎么实现呢?

### ISSUE THREAD

**Issue by lff2018** [ant-design/ant-design-mini#694]
![image](https://user-images.githubusercontent.com/47960944/233525952-bb749405-4f05-4b72-8b60-c3d684eab909.png)

如图:  已按照官方文档进行设置   但是没生效

## 期望
有没有具体的实现方法

**Comment by jc9702507** [comment]
可以这样来自定义其他
```json
{
  "format": 2,
  "compileOptions": {
    "less": {
      "modifyVars": {
         colorPrimary: "red",
         colorWathet: "blue"
      }
    }
  }
}
```

**Comment by lff2018** [comment]
是按照这样定义的呢    但是没生效

**Comment by lff2018** [comment]
![image](https://user-images.githubusercontent.com/47960944/233527898-edc083c8-26e4-4eb1-9843-ec48f8687873.png)
![image](https://user-images.githubusercontent.com/47960944/233527915-deda7a4f-bee4-424e-93a2-519c5457fb8b.png)

**Comment by jc9702507** [comment]
import的需要是less，比如"button": "antd-mini/less/Button/index"

**Comment by lff2018** [comment]
好的,已经解决了  谢谢!
