### ISSUE TITLE
tabs 标签页  滑动   左右滑动时  整个页面滑动了

### ISSUE THREAD

**Issue by lff2018** [ant-design/ant-design-mini#695]
## 背景
tabs 标签页  滑动   左右滑动时  整个页面滑动了

是什么原因导致了这种情况呢?

## 期望
只滑动标签页   不滑动页面

https://user-images.githubusercontent.com/47960944/233527442-0ce21da4-3531-4eb4-af31-2fac5840b546.mp4

**Comment by jc9702507** [comment]
可发下你的js，axml

**Comment by lff2018** [comment]
[js.txt](https://github.com/ant-design/ant-design-mini/files/11291909/js.txt)
[axml.txt](https://github.com/ant-design/ant-design-mini/files/11291910/axml.txt)

**Comment by jc9702507** [comment]
```html
<view class="content" style="padding-top: {{navigatorHeight}}px">
  <view class="container">
    <tabs-v1 items="{{items}}" />
  </view>
  <view class="menu">
    <tabs-v1 items="{{items}}" type="capsule" />
  </view>
</view>
```
修改为这个试试，应该是你的css问题

```html
<tabs-v1 items="{{items}}" />
<tabs-v1 items="{{items}}" type="capsule" />
```

**Comment by lff2018** [comment]
已经好了   样式的设置问题
