### ISSUE TITLE
钉钉小程中: 自定义表单后 报错问题 

### ISSUE THREAD

**Issue by wyxsummer520** [ant-design/ant-design-mini#700]
af-appx.worker.min.js:26 TypeError: $sjs_options.$sjs_find is not a function

setData(...) can only update a mounted component. This usually means you called setData() on a unmounted component. Please check the code for the "/pagesA/yp/shouy/sydj/checklist/checklist" component of "pagesA/yp/shouy/sydj/sydj" page.

af-appx.worker.min.js:26 $sjs_options.$sjs_find is not a function
Please check your axml: 
    in /pagesA/yp/shouy/sydj/checklist/checklist
    in pagesA/yp/shouy/sydj/sydj

**Comment by jc9702507** [comment]
钉钉里sjs无法使用find，修改为：
```js
let obj;
options.forEach(item => {
  if (item.value === value) {
    obj = item;
  }
});
if (obj) {
  return obj.title;
}
```
