### ISSUE TITLE
popup组件内使用range-picker，选择日期面板位置错误

### ISSUE THREAD

**Issue by mustars** [ant-design/ant-design-mini#702]
## 组件

range-picker
## 基础库版本

- [x] 1.x
- [ ] 2.x

## 手机系统

- [x] iOS
- [x] Android
- [ ] HarmonyOS

## 组件库版本 

^1.6.0

## 预期行为 

popup组件设置position="top"，popup内使用range-picker，应该弹出在底部。

## 复现步骤 

1. popup组件设置position="top"
2. popup内使用range-picker
3. 打开range-picker，日期选择框位置异常

## 复现 demo

[test.zip](https://github.com/ant-design/ant-design-mini/files/11307750/test.zip)

**Comment by mustars** [comment]
![image](https://user-images.githubusercontent.com/26319610/233930930-f6c5dda1-8750-4eb0-9ab1-33eef23ed18b.png)
![image](https://user-images.githubusercontent.com/26319610/233931174-77a1f7b3-ab32-4d71-a690-52149cb4a89b.png)

**Comment by jc9702507** [comment]
使用最新的antd-mini，加了props解决这个问题
