### ISSUE TITLE
stepper步进器，stepper组件的value和内部的input value不一致

### ISSUE THREAD

**Issue by V66628** [ant-design/ant-design-mini#706]
stepper步进器，stepper组件中当组件内部的input组件未失去焦点的时候它的value和stepper组件的 value值不一致。
例如：
当组件输入时超过输入的范围，没有立即变到最高范围，必须得失去焦点才会变到最高范围。
<img width="340" alt="image" src="https://user-images.githubusercontent.com/82310573/234178837-493f0fbd-2f17-4b8f-b959-099b4f268051.png">

**Comment by jc9702507** [comment]
这个就是这样的，要blur才会修改为对的value，这样不会影响用户输入。可对比下antd组件。
