### ISSUE TITLE
请教下如何修改组件内的样式？

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design-mini#716]
![image](https://user-images.githubusercontent.com/8286897/236808783-e8199df6-cc4b-4856-9a9e-739a6c40b473.png)
我使用了action-sheet组件，我想修改 ant-actionsheet-list-item 的样式，该如何做呢。

我传入了className，但是在less中写的样式好像是隔离的，并不会在组件内生效。
请教下如何做，才能修改组件内部样式呢？
![image](https://user-images.githubusercontent.com/8286897/236809604-8aaf58bd-ca6b-489a-b0f9-13de879bbdea.png)
![image](https://user-images.githubusercontent.com/8286897/236809719-9d56d886-74d1-43ad-b305-662348ae3d77.png)

**Comment by tulies** [comment]
搞定了，需要去掉 "styleIsolation": "apply-shared" 。

期望能够在ActionSheetItem上加上class 或者style的配置，来控制某个特定item的样式。

**Comment by jc9702507** [comment]
这是两个问题，要是使用了"styleIsolation": "apply-shared"，在ActionSheetItem上加上class 或者style也会没有作用
