### ISSUE TITLE
Result icon 颜色被覆盖。

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/ant-design-mini#72]
## 组件
- Result 操作结果

## 基础库版本

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2. 

## 复现 demo
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/4705237/164960528-9f0e5b41-c558-4533-83c5-c97e80bccc76.png">

**Comment by miaodongqing** [comment]
0.0.10版本已修复
