### ISSUE TITLE
picker组件，事件穿透

### ISSUE THREAD

**Issue by pijiupaowanzi** [ant-design/ant-design-mini#725]
## 组件
picker 

## 设备机型
iphoneSE
## 手机系统
IOS

## APP 
钉钉小程序

## 组件库版本 
1.7.0

## 预期行为 
picker组件下的选项，划动的时候不应该影响主页面

## 复现步骤 
1. 新增一个小程序页面，页面超过100vh
2. 添加一个picker组件，设置选项
3. 划动选项，可以看到选项滑动的同时，下方页面也在滑动

**Comment by jc9702507** [comment]
在IOS钉钉测试好像没问题呢，但是没有测试iphoneSE。是只是iphoneSE才有问题？

**Comment by pijiupaowanzi** [comment]
> 在IOS钉钉测试好像没问题呢，但是没有测试iphoneSE。是只是iphoneSE才有问题？

小程序开发者工具中是存在这样的问题，我想当然的认为手机上也这样。刚开始写小程序（抱歉抱歉抱歉）

**Comment by bytemain** [comment]
IDE 3.7.2 修复了这个问题：https://opendocs.alipay.com/mini/ide/beta_log
<img width="573" alt="CleanShot 2023-05-16 at 17 54 34@2x" src="https://github.com/ant-design/ant-design-mini/assets/13938334/952ddcdc-8176-433c-ace7-7b6b5a91e2db">
