### ISSUE TITLE
divide组件与自定义组件使用时报错

### ISSUE THREAD

**Issue by aShu-guo** [ant-design/ant-design-mini#727]
## 组件
divide组件

## 基础库版本
- [1.25.7] 1.x

## 设备机型
mac os

## APP 
钉钉小程序（在小程序开发工具中预览即可）

## 组件库版本 
1.6.3

## 预期行为 
编译之后，页面可以正常展示

## 复现步骤 
1. 小程序开发工具编译即可
出现报错：
<img width="693" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/65716236/17d5e433-9a2d-44e2-ad6f-3ee33a5adba4">

阅读了https://opendocs.alipay.com/mini/framework/auge4r ，其中有提到上述问题，但是排查了之后发现开启了component2编译。而且如果不引用divide组件便可以编译成功。

## 复现 demo
https://github.com/aShu-guo/ant-mini-divide

**Comment by jc9702507** [comment]
使用你发的测试，没有报错呢

**Comment by bytemain** [comment]
我来看下

**Comment by bytemain** [comment]
可以复现，我们这边的结论：
1. 如果开启 component2，该问题必须升级到小程序基础库 2.0 才能解决。
2. 钉钉目前无法使用小程序基础库 2.0，我们帮忙推进钉钉升级。

感谢你的反馈。
