### ISSUE TITLE
1.8.0 启用component2以后Stepper 步进器样式出现错位

### ISSUE THREAD

**Issue by weiiz** [ant-design/ant-design-mini#738]
## 组件
Stepper 步进器

## 基础库版本
SDKVersion: 2.8.5
## 设备机型
iPhone12
## 手机系统
IOS
## 组件库版本 
1.8.0

## 预期行为 
步进器按钮对齐

## 复现步骤 
ide启用component2，允许动态加载组件 
Stepper 步进器的加减号按钮会出现错位，关闭component2后恢复正常

**Comment by jc9702507** [comment]
是支付宝还是钉钉？可发下图片

**Comment by weiiz** [comment]
![步进器](https://github.com/ant-design/ant-design-mini/assets/57380836/fda0ec82-67a7-4789-9467-b9417850883d)

> 是支付宝还是钉钉？可发下图片

支付宝小程序

**Comment by jc9702507** [comment]
使用了 “允许动态加载组件” 加载css顺序好像会被修改，这个好像是小程序问题。antd-mini可能不是很方便修改，提了一个PR #743 但是这个PR只是改了这个bug，其实还有其他的问题。另外这个PR修改是通过`!important`来解决，但是会对自定义className带来问题
