### ISSUE TITLE
checkbox-group 不能在钉钉小程序中引入

### ISSUE THREAD

**Issue by eyouhi** [ant-design/ant-design-mini#74]
## 组件

checkbox-group
## 基础库版本
0.0.8

- [ ] 1.x
- [ ] 2.x

## 手机系统
iphone12
- [ ✅] iOS
- [ ] Android
- [ ] HarmonyOS

## 组件库版本 

0.0.8
## 预期行为 

Error: Tried to merge two objects with the same key: `value`. This conflict is due to `props` of a component mixin.
    at Ho (af-appx.worker.min.js:26)
    at zo (af-appx.worker.min.js:26)
    at r (af-appx.worker.min.js:26)
    at Object./node_modules/antd-mini/es/CheckboxGroup/index (af-appx.worker.min.js:26)
    at Object.getComponent (af-appx.worker.min.js:26)
    at so (af-appx.worker.min.js:26)
    at ei.startRender (af-appx.worker.min.js:26)
    at ei.load (af-appx.worker.min.js:26)
    at af-appx.worker.min.js:26
    at jo (af-appx.worker.min.js:26)
## 复现步骤 

1. 倒入组件
2. 运行报错

**Comment by Alpsli** [comment]
解决办法： mini.project.json开启以下配置
{
  "enableAppxNg": true,
  "enableNodeModuleBabelTransform": true
}

**Comment by eyouhi** [comment]
> 解决办法： mini.project.json开启以下配置 { "enableAppxNg": true, "enableNodeModuleBabelTransform": true }
[cg-demo.zip](https://github.com/ant-design/ant-design-mini/files/8587610/cg-demo.zip)

依然是此报错，就checkbox-group这个组件出现，其他的未见到

**Comment by Alpsli** [comment]
![image](https://user-images.githubusercontent.com/52439609/167234148-6ef480e5-a206-4914-8107-3acb14290caf.png)
我试了一下你这个demo，加了 {
  "enableAppxNg": true,
  "enableNodeModuleBabelTransform": true
}
这个配置是可以ok的

**Comment by tpc707494** [comment]
配置了还是报错
![image](https://user-images.githubusercontent.com/16035185/167550442-3b8f225a-595a-471d-9482-c582b243ab67.png)
去掉了就正常了
![image](https://user-images.githubusercontent.com/16035185/167550865-7f5d65f0-dda8-4fc7-9710-524bfccebfee.png)

**Comment by Alpsli** [comment]
这个问题我们会修掉

**Comment by miaodongqing** [comment]
0.0.10 版本已修复

**Comment by miaodongqing** [comment]
0.0.10 版本已修复
