### ISSUE TITLE
希望插槽之类的文档能够写的详细点 

### ISSUE THREAD

**Issue by zhumengyua** [ant-design/ant-design-mini#744]
## 背景
 
在使用时间选择器的时候，文档写的是：
![image](https://github.com/ant-design/ant-design-mini/assets/32129847/141098a8-b938-496e-91b2-e562b20961c1)
但是其实实际是 content应该是插槽名 
对于一个新手可能有点感觉文档写的很混淆，试了一会才意识到这是插槽名，我看了其他的文档基本会把插槽单独列为一列写出来，不会混到属性中显示

## 期望
 
单独列一段文档作为插槽名

## 思路
 
单独列一段文档作为插槽名

**Comment by jc9702507** [comment]
可以加一个对于类型是 slot的说明，但是slot跟其他属性都是相同的作为一个属性，对比其他的也是这样的文档。另外你的问题是解决了？只是说issue的问题？

**Comment by zhumengyua** [comment]
只是文档写的问题，我的问题已经解决了
