### ISSUE TITLE
android 中，受控模式的input 输入出现内容错误问题

### ISSUE THREAD

**Issue by diaogedd** [ant-design/ant-design-mini#753]
## 组件
input

## 基础库版本

2.0

## 设备机型
xiaomi13

## 手机系统
 Android

## 组件库版本 
v1

## 复现步骤 
初步估测所有Android机器都会有这个问题
<img width="1255" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/73161620/6b1b3d1f-06b7-4a44-9768-efc6d5a5ce86">
Android系统手机，扫官网的二维码进去，就会有问题，本地拉代码用安卓机扫码也有相同的问题。

##复现视频

https://github.com/ant-design/ant-design-mini/assets/73161620/bd150ecd-cdee-4661-9142-a5ed935689c6

**Comment by jc9702507** [comment]
这个是有的android手机会有这个问题，可使用：
![image](https://github.com/ant-design/ant-design-mini/assets/113670357/89f8a60e-ea11-44da-8aaa-b9d2747c1e0f)

**Comment by diaogedd** [comment]
哈？ 又是没仔细看文档的一天。
