### ISSUE TITLE
collapse默认展开不生效

### ISSUE THREAD

**Issue by dnn12366013** [ant-design/ant-design-mini#756]
<collapse
      defaultCurrent="{{current}}"
      current="{{current}}"
      items="{{listData}}"
      onChange="onChange"
    >
    <view slot="title" slot-scope="item" class="title">
      <image mode="scaleToFill" src="/imagesNew/interaction/ask.png"  class="askIcon" />
      <view >
        {{item.value.title}}
      </view>
    </view>
    <view slot="content" slot-scope="item" class="content">
      <image mode="scaleToFill" src="/imagesNew/interaction/answer.png"  class="askIcon1" />
      <view >
        {{item.value.summary}}
        <image mode="scaleToFill" src="{{item.value.firstPicPath}}" class="contentImg"/>
      </view>
    </view>
  </collapse>
内容都是通过插槽修改的样式，items对应的是didMount内调用接口获取的

**Comment by jc9702507** [comment]
发下js，current是什么，对比文档，current需要array

**Comment by jc9702507** [comment]
那应该没问题，可上传一个最小可用的项目不

**Comment by dnn12366013** [comment]
"antd-mini": "^0.0.16",
  "antd-mini-v1": "npm:antd-mini@^1.9.0",
我下载了没问题可以默认展开，但是我这个是老项目0.x跟1.x一起使用，折叠面板用的1.8和1.9都不行 
"collapse": "antd-mini-v1/es/Collapse/index"

**Comment by dnn12366013** [comment]
找到问题了，先在外层a:if判断一下这个接口的数据拿到了吗

**Comment by throneoftheGame** [comment]
> 找到问题了，先在外层a:if判断一下这个接口的数据拿到了吗

老哥，牛牪犇逼
