### ISSUE TITLE
数组数据循环使用form-input赋值问题

### ISSUE THREAD

**Issue by wyxsummer520** [ant-design/ant-design-mini#757]
<view class="form-detail">
  <view a:for="{{ list }}" a:for-item="item" a:key="index">
    <form-input label="{{index+1}}" name="value{{index}}" placeholder="请输入" type="number" allowClear maxlength="300" ref="handleRef" />
  </view>
  <view class="mar_t_20">
    单件验证均重(公斤):{{sjyzjz}}
  </view>
</view>

import { Form } from 'antd-mini/es/Form/form';
Page({
  data() {
    return {
      list: [1, 2, 2, 0, 0, 0, 6, 0, 0, 8],
      sjyzjz: ''
    }
  },
  form: new Form({}),
  handleRef(ref) {
    this.form.addItem(ref);
  },
  onLoad() {
    let list = this.data.list;
    list.forEach((ele,idx) =>{
      this.form.setInitialValues({
        ['value' + `${idx}`]: ele
      });
    })
  },
});

**Comment by jc9702507** [comment]
```js
import { Form } from 'antd-mini/es/Form/form';
Page({
  data() {
    return {
      list: [1, 2, 2, 0, 0, 0, 6, 0, 0, 8],
      sjyzjz: ''
    }
  },
  form: new Form({}),
  handleRef(ref) {
    this.form.addItem(ref);
  },
  onLoad() {
    let list = this.data.list;
    const initialValues = {}; 
    list.forEach((ele,idx) =>{
      initialValues['value' + idx] = ele;
    })
    this.form.setInitialValues(initialValues);
  },
});
```

**Comment by wyxsummer520** [comment]
<view class="form-detail">
  <view a:for="{{ list }}" a:for-item="item" a:key="index">
    <form-input label="{{index+1}}" name="value{{index}}" placeholder="请输入" type="number" allowClear maxlength="300" ref="handleRef" />
  </view>
  <view class="mar_t_20">
    单件验证均重(公斤):{{sjyzjz}}
  </view>
</view>

**Comment by wyxsummer520** [comment]
```
  <view a:for="{{ list }}" a:for-item="item" a:key="index">
    <form-input label="{{index+1}}" name="value{{index}}" placeholder="请输入" type="number" allowClear maxlength="300" ref="handleRef" />
  </view>
```
