### ISSUE TITLE
input 和 picker混用，input不能失焦

### ISSUE THREAD

**Issue by pijiupaowanzi** [ant-design/ant-design-mini#758]
## 组件
input

## 设备机型
IOS设备

## APP 
钉钉小程序

## 组件库版本 
1.7.0

## 预期行为 
input输入过程中，触发picker组件应该失焦

## 复现步骤  
1.新建input组件和picker组件
2.input输入内容的过程中，点击picker组件
3.此时手机键盘未消失，input还可以继续输入

## 复现 demo
<list-item>
  <input/>
</list-item>
<list-item>
  <picker />
</list-item>
图片：
![image](https://github.com/ant-design/ant-design-mini/assets/68858350/bc5bde37-3578-443b-8ec5-35921133ba84)

**Comment by jc9702507** [comment]
发下js, axml

**Comment by pijiupaowanzi** [comment]
> 发下js, axml

axml
```
   <list>
      <list-item>
        <textarea value="{{inputValue}}" onChange="getValue"/>
      </list-item>
      <list-item>
        <picker 
          slot="extra"
          onOk="checkDay"
          options="{{weekList}}" 
          value="{{pickerValue}}"
        />
      </list-item>
    </list>
```
    inputValue: '',
    pickerValue: '',
    weekList: [
      { label: '周一', value: 'Mon' },
      { label: '周二', value: 'Tues' },
      { label: '周三', value: 'Wed' },
      { label: '周四', value: 'Thur' },
      { label: '周五', value: 'Fri' },
    ],
methods
```
   getValue(value) {
      this.setData({
        inputValue: value
      })
    },
    checkDay(value) {
      this.setData({
        pickerValue: value
      })
    },
```
Android是正常的

**Comment by jc9702507** [comment]
测试了，这个是钉钉小程序的问题。不是antd-mini问题，支付宝小程序没这个问题。

```html
<input />
<view onTap="onTap">请选择</view>
<view a:if="{{visible}}">
  popup show
</view>
```

```js
Page({
  data: {
    visible: false,
  },
  onTap() {
    this.setData({
      visible: !this.data.visible,
    });
  },
});
```

用这个来测试，在钉钉小程序里，先点input有输入框，再去点“请选择”，键盘不会收起。
