### ISSUE TITLE
range-picker组件交互问题

### ISSUE THREAD

**Issue by aShu-guo** [ant-design/ant-design-mini#759]
## 组件
range-picker

## 基础库版本

- 1.25.7

## 设备机型

小程序开发者工具

## 组件库版本 
1.6.3

## 预期行为 
当初始值的开始时间小于结束时间时，滑动picker上的开始时间应该根据用户滑动来更改，组件内部不应限制开始时间的最大值。

这样如果用户想让开始时间大于结束时间，就只能先去修改结束时间，再去修改开始时间了

## 复现步骤 
1. 默认值为：2022/03/21 - 2022/05/20，滑动开始时间的年份到2023
2. 发现开始时间最大只能为2022/05/20

## 复现 demo
官方文档中的demo即可复现：https://mini.ant.design/components/date-picker#rangepicker

**Comment by jc9702507** [comment]
当前：这个是开始时间要小于结束时间。要是修改为可以开始时间大于结束时间，那开始时间选择后就需要让结束时间先置空，用户再去选择结束时间，要是用户没选择就认为取消选择。

**Comment by aShu-guo** [comment]
我尝试了onPickerChange来监听开始时间的改变，但是组件内部对开始时间的限制似乎早于onPickerChange的执行

```html
// index.axml
<range-picker
              precision="month"
              placeholder="请选择"
              title="日期选择"
              defaultValue="{{dateRange}}"
              onPickerChange="onPickerChange"
              onOk="handleRangeOk"
      >
</range-picker>
```

```js
import dayjs from 'dayjs';

Page({
  data: {
    dateRange: [dayjs().subtract(5, 'months').toDate(), dayjs().toDate()],
  },
  onPickerChange(date, dateStr) {
    console.log(date, dateStr);
  },
  handleRangeOk(date) {
    this.setData({
      'dateRange[0]': date[0],
      'dateRange[1]': date[1],
    });
    //   请求接口
  },
});

```
