### ISSUE TITLE
选择器能否增加搜索功能当选择项太多的时候不好选

### ISSUE THREAD

**Issue by erpcto** [ant-design/ant-design-mini#764]
## 背景
 
当选择器有100个选项，要拉很久

## 期望
 
我是想在选择的时候能输入 过滤选择项

## 思路
 
<img width="281" alt="12d0535fc7392dac20d04e88953f3291" src="https://github.com/ant-design/ant-design-mini/assets/51810175/811becd1-f177-487d-bbb6-c78172f65c13">

https://github.com/ant-design/ant-design-mini/assets/51810175/5cca3601-cc57-4fae-b7ed-6146ca4802be

**Comment by jc9702507** [comment]
https://jc9702507.github.io/ant-design-mini/components/select

**Comment by erpcto** [comment]
1.list 这个，应该设计到data里面，方便赋值数据。 可以用两个list 在data 一个是原来的数据，一个是过滤后的数据，不需要在外部去创建 变量
在  onLoad(query)  启动时
![image](https://github.com/ant-design/ant-design-mini/assets/51810175/bc8d1e11-f15b-4bf4-aeaa-54c915251f11)
这样能用。

2.这个选择器没有 name 与 value   
单独的 value 某些场景不合用。
