### ISSUE TITLE
form的onValuesChange监听

### ISSUE THREAD

**Issue by zhangpiao96** [ant-design/ant-design-mini#772]
## 组件

Form

## 基础库版本
v1.9.2

钉钉
跳转含有form（有ValuesChange监听事件）的界面，返回，然后再跳转含有form（有ValuesChange监听事件）的同一个界面，form更改值时，会触发两次ValuesChange监听事件（就是跳转几次，更改form内容时，就会触发几次ValuesChange监听事件）。

**Comment by jc9702507** [comment]
发下js

**Comment by zhangpiao96** [comment]
import {
  Form
} from 'antd-mini-v1/es/Form/form';

Page({
  data: {
    position: 'horizontal',
  },
  form: new Form(),

  onReady() {
    this.form.onValuesChange((changedValues, allValues) => {
      console.log(changedValues);
    });
  },

  handleRef(ref) {
    this.form.addItem(ref);
  },

  reset() {
    this.form.reset();
  },

  toggle() {
    this.setData({
      position: this.data.position === 'horizontal' ? 'vertical' : 'horizontal',
    });
  },

  async submit() {
    const values = await this.form.submit();
    my.alert({
      title: '提交',
      content: JSON.stringify(values),
    });
  }
});

我会反复操作：跳转这个界面，返回，再跳转，就是导致多次绑定了，那我该怎么绑定呢

**Comment by jc9702507** [comment]
这个应该是钉钉小程序中的问题：页面跳转了，但是小程序页面还没有被unLoad，再次进入页面，调用了onReady。
你可以尝试这样解决：

修改onReady为这样
```js
import { Form } from 'antd-mini-v1/es/Form/form';

Page({
  data: {
    position: 'horizontal',
  },
  
  onShow() {
    this.form = new Form();
  },
  
  onReady() {
    this.form.onValuesChange((changedValues, allValues) => {
      console.log(changedValues);
    });
  },
  
  handleRef(ref) {
    this.form.addItem(ref);
  },
  
  reset() {
    this.form.reset();
  },
  
  toggle() {
    this.setData({
      position: this.data.position === 'horizontal' ? 'vertical' : 'horizontal',
    });
  },
  
  async submit() {
    const values = await this.form.submit();
    my.alert({
      title: '提交',
      content: JSON.stringify(values),
    });
  }
});

```

**Comment by zhangpiao96** [comment]
可以了，谢谢
