### ISSUE TITLE
纵向的tabs的scroll-view容器可以支持透传scroll-top、scroll-into-view等属性吗

### ISSUE THREAD

**Issue by dossweet** [ant-design/ant-design-mini#778]
## 背景
纵向的tabs的 [scroll-view](https://opendocs.alipay.com/mini/component/scroll-view?pathHash=8292073d) 容器不支持透传scroll-top、scroll-into-view属性

## 期望
纵向的tabs的scroll-view容器可以支持透传scroll-top、scroll-into-view等属性

## 思路
<img width="1422" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/38655923/018553e7-383e-4303-901c-044632842337">

**Comment by jc9702507** [comment]
应该可以的

**Comment by jc9702507** [comment]
好像只需要让纵向的tabs才能选中后可以有scrollMode

**Comment by jc9702507** [comment]
使用最新的antd-mini，纵向tabs选中的也可以在可视区域
