### ISSUE TITLE
swipe-action滑动组件

### ISSUE THREAD

**Issue by Selinahann** [ant-design/ant-design-mini#779]
## 组件
swipe-action滑动组件

## 预期行为 

组件正常情况下是可以滑动的，但是如果通过按钮点击动态展示组件，组件内部不能滑动。
`<view class="content">
    <view class="title" onTap="onclick">
      点击
    </view>
    <pop-up visible="{{showaddress}}" position="bottom" zIndex="2001" height="{{500}}" onClose="addressPopup">
		<view a:for="{{ 10 }}" class="t-swipe-item-con">
            
            <swipe-action
              data-item="{{ index }}"
              rightButtons="{{ rightBtns }}"
              elasticity="{{true}}"
              swiped="{{ swipeIndex === index }}"
              onSwipeEnd="onSwipeEnd"
              onSwipeStart="onSwipeStart"
              onButtonTap="onButtonTap"
              >
              <view class="t-swipe-item-con-view">
                右侧-三个按钮
              </view>
            </swipe-action>
        </view>
    </pop-up>
</view>`
`Page({
     onclick(){
          this.setData({
               showaddress: true
          })
     }
})`

**Comment by jc9702507** [comment]
popup destroyOnClose="{{true}}"
