### ISSUE TITLE
antd-mini在小程序插件内报错：【插件公开组件的 acss 文件不支持使用 "元素选择器"】

### ISSUE THREAD

**Issue by Frank1e0927** [ant-design/ant-design-mini#807]
## 组件

https://ant-design-mini.antgroup.com/components/empty

## 基础库版本

2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 组件库版本 
"@alipay/minifish": "^2.2.0",
"antd-mini": "^1.10.4",

## 复现步骤 

1. 支付宝小程序插件安装antd-mini ，引用empty组件
2. 在axml中引入，报错 【插件公开组件的 acss 文件不支持使用 "元素选择器"】

## 复现 demo

![image](https://github.com/ant-design/ant-design-mini/assets/17680956/1c2b6dac-7aaa-4380-9270-f0e9bd72d328)
![image](https://github.com/ant-design/ant-design-mini/assets/17680956/e3a8e0b5-9302-4255-9c98-88f63ce7f24d)

**Comment by DiamondYuan** [comment]
![image](https://github.com/ant-design/ant-design-mini/assets/9692408/8c39b8fd-feac-434c-af80-e17ebdb9ab67)


empty 组件里用到了 image 标签，而小程序插件不支持。

我提一个 pr 修复一下

**Comment by DiamondYuan** [comment]
已修复
