### ISSUE TITLE
钉钉小程序 通过 dd.navigateTo跳转页面第二次报错，请问怎么解决呢

### ISSUE THREAD

**Issue by luoxin59420** [ant-design/ant-design-mini#812]
c60cc657-1a23-4b2d-b0a0-82e431348ce8:1 Error: Form "addItem" same name: "priority"
    at Form.addItem (form.js:396:1)
    at Object.handleRef (index.js:127:1)
    at a.<computed>.a.<computed> (VM62 af-appx.worker.min.js:26:128446)
    at Hr (VM62 af-appx.worker.min.js:26:51532)
    at Vr (VM62 af-appx.worker.min.js:26:47622)
    at Fr (VM62 af-appx.worker.min.js:26:47126)
    at Object.batchedUpdates (VM62 af-appx.worker.min.js:26:53479)
    at Ba (VM62 af-appx.worker.min.js:26:114154)
    at wo.renderVDOM (VM62 af-appx.worker.min.js:26:134158)
    at wo.startRenderVDOM (VM62 af-appx.worker.min.js:26:137859)

**Comment by DiamondYuan** [comment]
能写一个简答的复现 demo 吗？ 我试了一下 navigateTo 没有报错。

**Comment by luoxin59420** [comment]
先跳转到 表单页面赋值给表单，然后返回 再跳进去就报这个 Form "addItem" same name了，跳转api：dd.navigateTo({
      url: `/pages/index/view/index?id=${this.data.pageData.id}`,
      success: () => {},
      fail: () => {},
      complete: () => {},
    });

页面初始化有用到： form: new Form(),
  handleRef(ref) {
    this.form.addItem(ref)
  },

**Comment by DiamondYuan** [comment]
> 先跳转到 表单页面赋值给表单，然后返回 再跳进去就报这个 Form "addItem" same name了，跳转api：dd.navigateTo({ url: `/pages/index/view/index?id=${this.data.pageData.id}`, success: () => {}, fail: () => {}, complete: () => {}, });
> 
> 页面初始化有用到： form: new Form(), handleRef(ref) { this.form.addItem(ref) },



是不是多个页面用了同一个 form ?

同一个页面的 handleRef 应该只会被调用一次。

**Comment by DiamondYuan** [comment]
能建一个完整项目吗？ 上面的例子我这边没办法复现

**Comment by DiamondYuan** [comment]
> 我怎么把项目给到你看呢 我这边每个页面都是单独的form

建一个空项目，然后写一个简单的 form ？

**Comment by lianjianjie** [comment]
我也遇到了同样的问题，钉钉小程序，表单返回再次进入就会报错
![image](https://github.com/ant-design/ant-design-mini/assets/16377699/7d2aaab0-8d94-4dfd-89a5-e16ba9cb9a1a)

**Comment by lianjianjie** [comment]
@luoxin59420 请问你解决了吗，我这里也遇到了同样的问题

**Comment by DiamondYuan** [comment]
> @luoxin59420 请问你解决了吗，我这里也遇到了同样的问题

写一个复现的 demo ？

**Comment by lianjianjie** [comment]
@DiamondYuan  您看可以用吗
https://github.com/lianjianjie/test.git

**Comment by luoxin59420** [comment]
已解决，但不佳；因为dd.navigateTo跳转到的页面没有被销毁，导致每次进入页面的时候都会执行form表单的handleRef，导致出现这个问题，可以通过：dd.redirectTo（跳转到应用内的某个指定页面，并关闭当前页面） 或者 dd.reLaunch（关闭所有页面）

**Comment by lianjianjie** [comment]
@luoxin59420 感谢，和我的想法基本一样

**Comment by DiamondYuan** [comment]
form 的 item 是不支持重复添加的，所以如果页面没有销毁，再次访问就会报错。

如果页面是多次访问，可以在 addItem 之前判断一下之前是否添加过

    if(this.form.fields[ref.props.name]){
    this.form.addItem(ref);
    }
