### ISSUE TITLE
input 的 type 设置 number 无效

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design-mini#813]
<input type="number" value="测试" />

**Comment by DiamondYuan** [comment]
如果 value 设置了中文，那个 input 里实际显示的值会是中文。
点击后，会弹出数字输入框。

和 支付宝小程序 、微信小程序原生的 input 的表现相同。

**Comment by Parmerlee** [comment]
`<input placeholder="请输入账号" type="number" onChange="onMobileInput" maxLength={{11}} style="background: #ffffff" />`
我使用input标签，发生使用任何type都不生效。

**Comment by Parmerlee** [comment]
淘宝小程序的问题，与你们的组件库无关。
