### ISSUE TITLE
textarea 使用 onConfirm后无法清空输入的内容

### ISSUE THREAD

**Issue by wuhao5436** [ant-design/ant-design-mini#816]
## 组件
textarea

## 基础库版本

"version": "1.10.5"

## 设备机型

华为荣耀
iphone14

## 手机系统

- iOS
- Android
- HarmonyOS

## APP 
测试阶段

## 组件库版本 
"name": "antd-mini",
"version": "1.10.5",

## 预期行为 
```
 <textarea
      type="text"
      placeholder="你有什么购买需求吗"
      className="ipt"
      onChange="handleChange"
      onBlur="handleBlur"
      onConfirm="handleConfirm"
      auto-height="{{true}}"
      show-count="{{false}}"
      style="line-height: 0; padding-left: 14rpx; padding-top:10rpx"
      maxLength="140"
      ref="handelRef"
    />

 handleConfirm() {
   /** 文档提供的方法 */
   this.input.update('');
  /** 受控组件也不行 */
    this.setData({
      iptVal: ""
    })
}

调用完 handleConfirm 后输入框内容会被清空
```

## 复现步骤 

使用弹起来的软键盘的换行键 调用handleConfirm
bug： 输入框内容无法清空
this.input.data.mixin.value 还是之前的数值

但是：设置"发送"按钮 点击后调用handleConfirm 确可以清空内容

**Comment by DiamondYuan** [comment]
我试了一下。

1.  textarea 好像不支持 onConfirm ？ 我这边只有换行键

2. input 的 onConfirm 的确有问题，无法清空数据

**Comment by wuhao5436** [comment]
"usingComponents": {
    "textarea": "antd-mini/es/Input/Textarea/index",
  }
  
  我是这样引用的，onConfirm 事件能触发 
  this.input.update(''); 后
  this.input.data.mixin.value 还是原来的值

**Comment by DiamondYuan** [comment]
> "usingComponents": { "textarea": "antd-mini/es/Input/Textarea/index", }
> 
> 我是这样引用的，onConfirm 事件能触发 this.input.update(''); 后 this.input.data.mixin.value 还是原来的值


目前的流程是这样

1. 当前 input value 为 "1"
2. 按回车， 此时触发 onConfirm 事件 ，this.input.update 会触发 this.setData({ value: "" })
3. 因为输入了回车换行，触发了 onChange 事件，事件的 value 是 '1\n" 

textarea 支持输入多行， 无法区分是换行还是确认， 不建议使用 onConfirm 事件。

是有什么特殊需求吗？

**Comment by DiamondYuan** [comment]
> "usingComponents": { "textarea": "antd-mini/es/Input/Textarea/index", }
> 
> 我是这样引用的，onConfirm 事件能触发 this.input.update(''); 后 this.input.data.mixin.value 还是原来的值

提供两种解决方案。 这个 issue 我先关了，有问题可重新打开。

1. onConfirm 以后，忽略下一次的 change

```
Page({
  data: {
    textareavalue: ''
  },
  ignoe: false,

  handleChange(e) {
    if (this.ignoreNextChangeEvent) {
      this.ignoreNextChangeEvent = false
      return
    }
    this.setData({
      textareavalue: e
    })
  },
  handleConfirm() {
    this.ignoreNextChangeEvent = true
    this.setData({
      textareavalue: ''
    })
  }
});
```

2.  加一个延迟

```
  handleConfirm(){
    setTimeout(()=>{
        this.input.update('')
    }, 100)
  }
```
