### ISSUE TITLE
loading 组件不能在钉钉小程序中使用

### ISSUE THREAD

**Issue by eyouhi** [ant-design/ant-design-mini#82]
## 组件

loading
## 基础库版本

- [ ] 1.x
- [ x] 2.x

## 设备机型
 iphone12
pc 环境为 m1max芯片 mac studio 
## 手机系统

- [x ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

钉钉企业内部小程序
## 组件库版本 

0.0.8
## 预期行为 

显示loading
## 复现步骤 

1.   json文件 引入组件
2.  在axml文件中引入
3.  报错
![image](https://user-images.githubusercontent.com/47080137/167749502-87329116-f113-4786-88a7-169a175e27e7.png)

4. 控制台报警
af-appx.worker.min.js:26 $sjs_color.$sjs_startsWith is not a function
Please check your axml: 
    in /node_modules/antd-mini/es/Loading/index
    in view
    in pages/index/index

## 复现 demo

[cg-demo.zip](https://github.com/ant-design/ant-design-mini/files/8665886/cg-demo.zip)

**Comment by Alpsli** [comment]
在支付宝小程序IDE中工作正常，看着像是钉钉小程序sjs没有支持 startsWith，你可以通过在 loading 上先绑一个 color="" 避开这个判断呢，这个我们也修一下
![image](https://user-images.githubusercontent.com/52439609/167755965-a38911e9-2dea-4919-9e71-c7f55cc2ce1b.png)

**Comment by miaodongqing** [comment]
0.0.9 fixed
