### ISSUE TITLE
uni-app引入antd-mini编译运行正常，上传版本报错

### ISSUE THREAD

**Issue by Iamdog** [ant-design/ant-design-mini#829]
## 背景
 

<img width="565" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/15391299/14236464-fdb5-4a44-ad77-8ba7babc9a0e">

<img width="1022" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/15391299/564bf159-0b41-497e-b987-0688fd1c1b70">

error[Resolve]: pages/backcardtransact/backcardtransact.axml
cannot resolve module 'antd-mini/es/Icon/index'

error[Resolve]: pages/backcardtransact/backcardtransact.axml
cannot resolve module 'antd-mini/es/Icon/index'

error[Resolve]: pages/transactsign/transactsign.axml
cannot resolve module 'antd-mini/es/Icon/index'

error[Resolve]: pages/transactsign/transactsign.axml
cannot resolve module 'antd-mini/es/Icon/index'

## 期望
 
如何在uni-app中正确引入，目前已经npm正常安装了，支付宝小程序开发工具能正常预览和真机调试，上传版本时报错，劳烦大佬指点

**Comment by ottomao** [comment]
不要用 cnpm 装依赖，软链可能有问题，用 npm 或者 yarn

**Comment by Iamdog** [comment]
重新使用npm安装了一遍还是一样的结果，
编译模拟器真机运行都正常
上传版本报错
 





在 2023-09-13 10:02:39，"Otto Mao" ***@***.***> 写道：

不要用 cnpm 装依赖，软链可能有问题，用 npm 或者 yarn

**Comment by ottomao** [comment]
老的 node_modules 删完重装还是这个结果？ 给个可复现的最小用例吧，我们试试看

**Comment by Iamdog** [comment]
最小的案例可以试试，麻烦了。











在 2023-09-13 10:43:01，"Otto Mao" ***@***.***> 写道：

老的 node_modules 删完重装还是这个结果？ 给个可复现的最小用例吧，我们试试看

**Comment by Iamdog** [comment]
@ottomao 
目前配置了以下这个
<img width="1390" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/15391299/6404a9af-3d7e-40b0-8a8d-e9b985fee8d0">
上传版本成功了
