### ISSUE TITLE
uploader组件手动上传

### ISSUE THREAD

**Issue by luoxin59420** [ant-design/ant-design-mini#831]
请问怎么通过点击别的按钮，打开uploader组件的图片上传呢

**Comment by DiamondYuan** [comment]
可以使用 ref 来解决。

详细可以看这里 https://github.com/ant-design/ant-design-mini/pull/832/files#diff-76a28fbe7ce405990295c59fb6a016c44b91dc8046f4a3442fd370d44b348a8c
