### ISSUE TITLE
tabs的电梯模式使用时不符合预期

### ISSUE THREAD

**Issue by liria123** [ant-design/ant-design-mini#836]
## 组件
tabs的电梯模式

## 基础库版本

1.24.8

## 设备机型
蜻蜓f4设备

## APP 
支付宝小程序

## 组件库版本 
这里的组件 https://mini.ant.design/components/tabs#%E7%94%B5%E6%A2%AF%E6%A8%A1%E5%BC%8F

## 预期行为 
点击标题tab定位到内容标题

## 复现步骤 

1. 可发送文件压缩包
2. 可发送演示视频

**Comment by DiamondYuan** [comment]
如果 item 的高度会动态变化， 可以在每次点击的时候使用 getBoundingClientRect 计算尺寸
