### ISSUE TITLE
form-upload-image组件

### ISSUE THREAD

**Issue by kongruojun** [ant-design/ant-design-mini#839]
## 组件

form-upload-image

## 基础库版本

- [x] 1.x
- [ ] 2.x

## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS
- [x] 小程序开发工具模拟器

## APP 

dingtalk
## 组件库版本 

2.11
## 预期行为 

在ant-design-mini.antgroup.com上使用image-uploader说明页面提供的"自定义移除"功能演示，其所展示的情况为正常
移除图片受弹窗控制，并根据弹窗选择的确定和取消正确执行。
## 复现步骤 

1. 拷贝官方提供的"自定义移除"的js代码到小程序开发工具内使用
2. 选择图片执行onUpload成功上传到后端
3. 点击右上角移除图片的x，图片将直接被移除，无论选择确定或是取消，亦或是不点击弹窗按钮，图片移除不受弹窗控制。

**Comment by DiamondYuan** [comment]
已修复， https://github.com/ant-design/ant-design-mini/pull/842

**Comment by DiamondYuan** [comment]
2.12.0 已修复
