### ISSUE TITLE
钉钉小程序引入antd-mini:2.11.0后，form-cascader-picker受控模式不生效问题

### ISSUE THREAD

**Issue by rknie** [ant-design/ant-design-mini#840]
## 组件
form-cascader-picker

## 基础库版本
1.25.7

## 设备机型
安卓全系列

## 手机系统
Android

## APP 
钉钉小程序

## 组件库版本 
2.11.0

## 预期行为 
选择受控模式后，根据onOk回调去设置value的值，不知道是不是钉钉小程序版本问题，咨询钉钉开程序开发那边，回复钉钉小程序无法主动更新，下载的也是钉钉最新稳定版开发工具

## 复现步骤 
根据官方提示里面的步骤操作后，handleOk回调函数设置值时不生效，还是无显示

## 复现 demo
<form-cascader-picker
      label="地区选择："
      arrow
      options="{{list}}"
      value="{{value}}"
      onOk="handleOk"
      placeholder="请选择地区"
      allowClear
      required
      message="需要选择地区"
      ref="handleRef"
/>

**Comment by rknie** [comment]
我单独试用了<cascader-picker>组件的受控模式，发现没问题，进而我尝试不使用<form-cascader-picker>组件的受控模式value赋值，而是使用name={{key}}，然后使用this.form.setFieldValue('key', ['x','y']); 发现可以将<form-cascader-picker>组件的值改变

**Comment by rknie** [comment]
我单独试用了 cascader-picker 组件的受控模式，发现没问题，进而我尝试不使用form-cascader-picker组件的受控模式value='{{value}}'，this.setData({ value: value}) 赋值，而是使用name={{key}}，然后使用 this.form.setFieldValue('key', ['x','y']); 发现可以将组件的值改变

**Comment by DiamondYuan** [comment]
form-cascader-picker  应该是在 form 中使用的，是 cascader picker 的二次封装，不支持受控模式的。 

value 是通过 this.form.setFieldValue 控制的
