### ISSUE TITLE
SwipeAction组件虽然文档上有说建议在基础库2.X之上运行，可钉钉基础库版本更新不了，希望能完善下

### ISSUE THREAD

**Issue by rknie** [ant-design/ant-design-mini#847]
## 组件
SwipeAction

## 基础库版本
1.25.7

## 手机系统
- [ ] Android

## APP 
钉钉小程序

## 组件库版本 
2.11.0

## 预期行为 
正常的左滑列表中的单条数据后，会显示按钮操作

## 复现步骤 
按照antd-mini文档中SwipeAction 滑动组件的基础用法，样式始终往左偏移一部分，单击某一条数据后，又会恢复正常

## 复现 demo
完全按照文档中的步骤来的，一步不差，但是显示出来的样式有偏差
![image](https://github.com/ant-design/ant-design-mini/assets/67246732/791a7bb6-352d-458a-b661-5195f7826b11)

**Comment by ottomao** [comment]
联系钉钉的技术同学反馈下吧，把基础库版本抬起来
