### ISSUE TITLE
Slider 组件设置step属性为0.5时不生效

### ISSUE THREAD

**Issue by 15200596294git** [ant-design/ant-design-mini#864]
## 组件
Slider 

## 基础库版本
1.25.7

## 设备机型
MEIZU20pro

## 手机系统
Android

## APP 
钉钉小程序

## 组件库版本 
2.12.2

## 预期行为 
拖动时应该每次移动0.5格

## 复现步骤 

1. 使用Slider组件，设置step为0.5，并绑定一个变量值
2. 展示变量值，一步一步拖动Slider组件

**Comment by DiamondYuan** [comment]
已修复，明天发布

**Comment by DiamondYuan** [comment]
2.13.0

**Comment by 15200596294git** [comment]
好的大佬，可以啦！
