### ISSUE TITLE
form-image-upload无法设置defaultFileList和fileList

### ISSUE THREAD

**Issue by 11003** [ant-design/ant-design-mini#888]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2. 

## 复现 demo

![b904dea563914af368386295cec8ce67](https://github.com/ant-design/ant-design-mini/assets/35055270/71b4b18b-f02d-4969-9e38-295e7441899e)

```html
<form-image-upload
  label="图片上传"
  defaultFileList="{{defaultFileList}}"
  name="imageList"
  onUpload="onUpload"
  maxCount="{{3}}"
  tooltip="需要上传3张图片"
  ref="handleRef"
/>
```

```js
  data: {
    defaultFileList: [{
      url: 'https://gw.alipayobjects.com/mdn/rms_226d75/afts/img/A*znK_ToIL8rQAAAAAAAAAAAAAARQnAQ',
      status: 'done',
    }]
  },
```

结果：
![image](https://github.com/ant-design/ant-design-mini/assets/35055270/90daf832-4d05-4046-8854-58af3b55ff8e)

**Comment by DiamondYuan** [comment]
FormImageUpload 是在 form 里用的。 应该是通过 value 来设置默认值的

**Comment by DiamondYuan** [comment]
<form-image-upload
  name="images"
  ref="handleRef"
/>

new Form({
    initialValues: {
      images: [],
    },
  }),

这样控制

**Comment by 11003** [comment]
> new Form({ initialValues: { images: [], }, }),
> 
> 这样控制

嗯嗯，解决了。

```js
			//商品详情图
			newFormResult.detailsImages = newFormResult.detailsImages.map(url => ({
				url,
				status: 'done'
			}))
			//填充数据
			this.form.setInitialValues({
				...newFormResult
			})
```
