### ISSUE TITLE
Picker组件动态加载的数据，会报错。

### ISSUE THREAD

**Issue by Zxiaozhi** [ant-design/ant-design-mini#89]
## 组件

Picker
## 基础库版本

- [ ] 1.x
- [ √] 2.x

## 设备机型
OPPO Ace2

## 手机系统

- [ ] iOS
- [ √] Android
- [ ] HarmonyOS

## APP 

支付宝小程序
## 组件库版本 

0.0.9
## 预期行为 

onOk应该正常回调且不报错
现在报错了
（索引）:46 TypeError: Cannot read property '1' of undefined
    at Object.onChange (index.js:134)
    at e.invokeMethod (af-appx.worker.min.js:6)

## 复现 demo

test.js
`
Page({
  data: {
    runingListStr: [],
  },
  onLoad() {
    setTimeout(() => {
      this.setData({
        runingListStr: [['动态加载的选项1', '动态加载的选项2', '动态加载的选项3', '动态加载的选项4']]
      })
    }, 1000)
  },
  handleRuningOk() {
    console.log('handleRuningOk')
  },
});
`

test.axml
`
<view>
  <antd-picker cols="{{1}}" disabled="{{false}}" pickerholder="这是动态加载的" data="{{runingListStr}}" 
    onOk="handleRuningOk">
    <view slot="title">这是动态加载的</view>
  </antd-picker>
</view>
`

test.json
`
{
  "usingComponents": {
    "antd-picker": "antd-mini/es/Picker/index"
  }
}
`

**Comment by Alpsli** [comment]
好的，收到，这个我们会修复

**Comment by Zxiaozhi** [comment]
> 好的，收到，这个我们会尽快修复

还有个，就是组件我没有设置value，只用onOk来修改数据状态，就发现点开选择框后，不滚动切换选项，直接点击确定，ok回调不会执行，需要滚动一下选项再确定，ok回调才会执行。

```
test.js
Page({
  data: {
  	sourcesListStr: [['选项1', '选项2', '选项3']],
	sourceStr: ''
  },
  handleSourceOk(e) {
  	console.log('handleSourceOk', e)
  })
})


test.axml
<antd-picker onOk="handleSourceOk" pickerholder="请选择来源 >" data="{{sourcesListStr}}">
	<view slot="title">{{sourceStr || '请选择来源'}}</view>
</antd-picker>
```

**Comment by miaodongqing** [comment]
动态数组问题已修复0.0.10 已修复

**Comment by miaodongqing** [comment]
0.0.13已修复
