### ISSUE TITLE
Ant Design Mini 中的日历组件报错

### ISSUE THREAD

**Issue by lucy0421** [ant-design/ant-design-mini#890]
Ant Design Mini下下载的 日历组件 无法使用 

直接从网站上下下来的 也用了  npm i
其他的组件可以，这个不可以

![image](https://github.com/ant-design/ant-design-mini/assets/76091929/70583b0c-5dd3-40fb-ac06-4dae874e36cc)

**Comment by lucy0421** [comment]
为啥会出现这个 axmlon 后缀的

**Comment by ottomao** [comment]
清除缓存，重启 IDE，是否可解？

![CleanShot 2023-10-24 at 16 45 23@2x](https://github.com/ant-design/ant-design-mini/assets/1622697/3e636fc2-5c34-4c8d-90b5-abdc7cde6ff4)

**Comment by ottomao** [comment]
如果还有问题，贴一下引用组件的代码吧，包括 .json \ .axml \ .js（或ts)

**Comment by DiamondYuan** [comment]
![image](https://github.com/ant-design/ant-design-mini/assets/9692408/9ebd3b90-4d75-43af-be7d-32c16e9a57ca)

是不是拷贝了 ts 编写的 demo ？ 开启 ts 编译试试看 https://opendocs.alipay.com/mini/02zko2

**Comment by lucy0421** [comment]
> 如果还有问题，贴一下引用组件的代码吧，包括 .json \ .axml \ .js（或ts)

![image](https://github.com/ant-design/ant-design-mini/assets/76091929/1aa51e37-80c7-4dc9-9181-c6aa0c0c9ff3)
可以这划不动，看不到后面的页面代码

**Comment by lucy0421** [comment]
> ![image](https://user-images.githubusercontent.com/9692408/277605251-9ebd3b90-4d75-43af-be7d-32c16e9a57ca.png)
> 
> 是不是拷贝了 ts 编写的 demo ？ 开启 ts 编译试试看 https://opendocs.alipay.com/mini/02zko2

![image](https://github.com/ant-design/ant-design-mini/assets/76091929/74f53d8e-d68d-4f4c-b167-a8f25b2c0f6e)

**Comment by lucy0421** [comment]
修复了吗？

**Comment by DiamondYuan** [comment]
> 修复了吗？

这个是官网的问题，下载代码没下载全。

https://github.com/ant-design/ant-design-mini/tree/master/compiled/alipay/demo/pages/Calendar

可以先手动拷贝一下代码
