### ISSUE TITLE
input、textarea组件属性maxlength在支付宝中maxlength，组件中maxLength,导致不生效

### ISSUE THREAD

**Issue by YaWeiBoy** [ant-design/ant-design-mini#894]
input、textarea组件属性maxlength在支付宝中为maxlength，组件中maxLength,导致不生效，字母L要小写

**Comment by DiamondYuan** [comment]
antd-mini 的参数为 maxLength

支付宝原生的参数为 maxlength

如果是使用 antd-mini , 需要使用大写的 maxLength。 antd-mini 在传给原生组件的时候，会转换成 maxlength

**Comment by YaWeiBoy** [comment]
form-textarea 传maxLength不生效

**Comment by DiamondYuan** [comment]
> form-textarea 传maxLength不生效

2.14.0 刚刚修复这个问题。 请问你 ant design mini 的版本是什么

**Comment by YaWeiBoy** [comment]
我升级下，我也奇怪 看源码没问题 原来升级过了
