### ISSUE TITLE
元素input没有onChange事件，所以ant-input的onChange没有用

### ISSUE THREAD

**Issue by 11003** [ant-design/ant-design-mini#900]
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2. 

## 复现 demo

![image](https://github.com/ant-design/ant-design-mini/assets/35055270/04586ed2-43a1-4d60-a6e7-35d411a53e4f)
![image](https://github.com/ant-design/ant-design-mini/assets/35055270/c4320ab1-9bb9-4d31-ad6c-0ead47d38efe)

**Comment by DiamondYuan** [comment]
![image](https://github.com/ant-design/ant-design-mini/assets/9692408/c5c26fdc-620b-4628-9330-01f7cbd41890)


form input 用的是 antd mini 的 input 组件，是有 onChange 的

**Comment by DiamondYuan** [comment]
<form-input
  label="地址"
  name="address"
  placeholder="请输入地址"
  allowClear
  onChange="handleChange"
  ref="handleRef" />
  
  
  我试了一下，这样是有效的。
