### ISSUE TITLE
更新一下贡献指南

### ISSUE THREAD

**Issue by SanGuiChen** [ant-design/ant-design-mini#912]
## 背景
 
现在的贡献指南似乎并不适配当前的项目，想贡献有点找不着头脑
[贡献指南](https://github.com/ant-design/ant-design-mini/blob/master/CONTRIBUTE.md
)

**Comment by DiamondYuan** [comment]
这里忘记改了， 可以先看官网的贡献指南 

https://ant-design-mini.antgroup.com/guide/contribute

**Comment by DiamondYuan** [comment]
已更新地址
