### ISSUE TITLE
vtabs组件左侧tab滑动至底部以后切换不生效

### ISSUE THREAD

**Issue by gotSomeCool** [ant-design/ant-design-mini#92]
## 组件

Vtabs
## 基础库版本

- [ ] 1.x
- [ √ ] 2.x

## 手机系统

- [√ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 预期行为 

选中后不自动切换回原来的选项
## 复现步骤 

1. 
2.

**Comment by miaodongqing** [comment]
0.0.10已修复
