### ISSUE TITLE
表单自定义如何被触发onchange？

### ISSUE THREAD

**Issue by 11003** [ant-design/ant-design-mini#925]
代码如下：

## 父组件

```js
accountSourceOptions: [
	{
		key: 1,
		value: '支付宝'
	},
	{
		key: 3,
		value: '银行卡'
	}
]
```

```html
 <common-select-popup ref="handleRef" label="收款账户类型" name="sellerCollectAccountType" value="{{formResult.collectAccountType}}" placeholder="请选择" message="请选择收款账户类型" options="{{accountSourceOptions}}" required="{{true}}" popupType="list" />
```

### 期望事件

```js
onReady() {
    this.form.onValuesChange((changedValues, allValues) => {
        console.log(`allValuesText===>`, allValues)
    })
},
```

## 自定义的子组件

[select-popup.zip](https://github.com/ant-design/ant-design-mini/files/13330199/select-popup.zip)

**Comment by DiamondYuan** [comment]
你是希望开发一个类似于 FormInput 的组件吗？

**Comment by 11003** [comment]
> 你是希望开发一个类似于 FormInput 的组件吗？

对

**Comment by DiamondYuan** [comment]
> > 你是希望开发一个类似于 FormInput 的组件吗？
> 
> 对

1.  利用 form/createComponent  创建组件
2. 使用  this.emit('onChange', value); 通知数据变化

**Comment by 11003** [comment]
> > > 你是希望开发一个类似于 FormInput 的组件吗？
> > 
> > 
> > 对
> 
> 1. 利用 form/createComponent  创建组件
> 2. 使用  this.emit('onChange', value); 通知数据变化

大佬，可以具体一些吗？select-popup这个组件，我每个item选择的时候传出了一个onChange事件

```
if (this.props.onChange) {
    this.props.onChange(temp)
}
```

**Comment by DiamondYuan** [comment]
> > > > 你是希望开发一个类似于 FormInput 的组件吗？
> > > 
> > > 
> > > 对
> > 
> > 
> > 
> > 1. 利用 form/createComponent  创建组件
> > 2. 使用  this.emit('onChange', value); 通知数据变化
> 
> 大佬，可以具体一些吗？select-popup这个组件，我每个item选择的时候传出了一个onChange事件
> 
> ```
> if (this.props.onChange) {
>     this.props.onChange(temp)
> }
> ```


https://github.com/ant-design/ant-design-mini/blob/0ec940dabd980835ea881f2a7bb7f6264ba966d5/compiled/alipay/src/Form/FormPicker/index.ts#L9


可以参考这里的代码。

**Comment by 11003** [comment]
> > > > > 你是希望开发一个类似于 FormInput 的组件吗？
> > > > 
> > > > 
> > > > 对
> > > 
> > > 
> > > 
> > > 1. 利用 form/createComponent  创建组件
> > > 2. 使用  this.emit('onChange', value); 通知数据变化
> > 
> > 
> > 大佬，可以具体一些吗？select-popup这个组件，我每个item选择的时候传出了一个onChange事件
> > ```
> > if (this.props.onChange) {
> >     this.props.onChange(temp)
> > }
> > ```
> 
> https://github.com/ant-design/ant-design-mini/blob/0ec940dabd980835ea881f2a7bb7f6264ba966d5/compiled/alipay/src/Form/FormPicker/index.ts#L9
> 
> 可以参考这里的代码。
> 
> form 会监听组件 emit 的事件
> 
> https://github.com/ant-design/ant-design-mini/blob/0ec940dabd980835ea881f2a7bb7f6264ba966d5/compiled/alipay/src/Form/form.ts#L123


哦哦哦，原来如此
