### ISSUE TITLE
最新版本Icon组件样式不起作用

### ISSUE THREAD

**Issue by chengzishule** [ant-design/ant-design-mini#927]
## 组件

Icon组件配置颜色color/size不起作用
## 小程序组件版本
使用的组件版本2.14.0
## 设备机型
模拟器Iphone6

**Comment by DiamondYuan** [comment]
https://mini.ant.design/guide/migration-v1
0.x 到 1.x 版本， icon 有改动。

> 去掉的之前default的font-size。让icon使用不再必须要去修改size props，而是通过自身及上层font-size就可修改icon。这里也是对比了antd的做法。在antd-mini内部，也对所有使用icon的组件进行了修改，使用上传的class即可修改icon大小、颜色等；对于使用界面上，也重构了交互，实现了类似antd的icon查看及复制界面，让搜索使用icon更方便。
