### ISSUE TITLE
NoticeBar组件visible属性

### ISSUE THREAD

**Issue by ChenHuiMing44** [ant-design/ant-design-mini#932]
## 组件

![image](https://github.com/ant-design/ant-design-mini/assets/16046399/651f7b87-41c0-47ee-ab99-b00d6f0f6fd1)
2.14.0版本，NoticeBar文档中有写visible属性，但是使用发现不生效，然后查看下代码也没看到visible属性，是否存在未知信息？期望添加该属性

## 基础库版本

- [ ] 1.x
- [x] 2.x

**Comment by DiamondYuan** [comment]
感谢反馈， 这个应该是文档错误，我修复一下。
可以用 a:if , css 的 display:'none' 来替代 visible 。
