### ISSUE TITLE
钉钉小程序使用range-picker组件失效

### ISSUE THREAD

**Issue by StePhEnCuHui** [ant-design/ant-design-mini#943]
## 组件

<range-picker
      slot="extra"
      placeholder="请选择"
      defaultValue="{{defaultDateRange}}"
      onPickerChange="handlePickerRangeChange"
      onVisibleChange="handleTriggerPicker"
      onOk="handleRangeOk">
    </range-picker>
## 基础库版本
1.25.7
## 设备机型
Huawei Mate 30 Pro
## 手机系统

Android

## APP 
钉钉小程序

## 组件库版本 
2.0

## 预期行为 
正常情况下应该在页面中显示时间区间选择器（在使用form组件中的日期选择器时页面正常）

## 复现步骤 
加载页面即可

## 复现 demo

json：
{
  "defaultTitle": "点检记录",
  "usingComponents": {
    "avatar":"antd-mini/es/Avatar/index",
    "skeleton": "antd-mini/es/Skeleton/index",
    "switch": "antd-mini/es/Switch/index",
    "skeleton-avatar": "antd-mini/es/Skeleton/Avatar/index",
    "skeleton-title": "antd-mini/es/Skeleton/Title/index",
    "skeleton-button": "antd-mini/es/Skeleton/Button/index",
    "skeleton-paragraph": "antd-mini/es/Skeleton/Paragraph/index",
    "skeleton-input": "antd-mini/es/Skeleton/Input/index",
    "container": "antd-mini/es/Container/index",
    "date-picker": "antd-mini/es/DatePicker/index",
    "range-picker": "antd-mini/es/DatePicker/RangePicker/index",
    "list-item": "antd-mini/es/List/ListItem/index",
    "list": "antd-mini/es/List/index",
    "button": "antd-mini/es/Button/index"
  }
}

html：
<view>
  <container
    title="点检记录生成时间"
    className="container">
    日期范围
    <range-picker
      slot="extra"
      placeholder="请选择"
      defaultValue="{{defaultDateRange}}"
      onPickerChange="handlePickerRangeChange"
      onVisibleChange="handleTriggerPicker"
      onOk="handleRangeOk">
    </range-picker>
  </container>
  
  <container
    title="记录"
    className="container">
    <skeleton animate loading="{{show_loading}}" />
  </container>
</view>

js：
import { Form } from 'antd-mini/es/Form/form';

Page({
  URL: 'http://127.0.0.1:8000/',
  data: {
    records: [],
    show_loading: true,
    defaultDateRange: [new Date('2022/03/21'), new Date('2022/05/20')],
    user_info: {}
  },
  onLoad() {

  },
  onShow() {
    let _this = this
    dd.getStorage({
      key: "user_info",
      success: (res) => {
        _this.setData({
          user_info: res.data
        })
      }
    })
    // dd.httpRequest({
    //   url: _this.URL + 'sbdj/get_records_by_user/' + _this.data.user_info.name,
    //   headers: {
    //     'Content-Type': 'application/json'
    //   },
    //   method: 'GET',
    //   timeout: 30000,
    //   dataType: 'json',
    //   success: (res) => {
        
    //   },
    //   fail: (err) => {
    //     console.log(err)
    //   }
    // })
  },
  handleTriggerPicker(visible, e) {
    console.log('onVisibleChange', visible, e);
  },
  handlePickerRangeChange(type, date, dateStr, e) {
    console.log('onPickerRangeChange', type, date, dateStr, e);
  },
  handleRangeOk(date, format, e) {
    console.log('onRangeOk', date, format, e);
  },
});

**Comment by DiamondYuan** [comment]
<img width="1485" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/9692408/d0964071-e0bd-4108-8e39-6048ea84dcf9">

https://mini.ant.design/components/date-picker

这里下载的 demo 有效吗

**Comment by StePhEnCuHui** [comment]
您好，我发现是不能放在 container 容器中，range-picker 组件在container组件中就失效了？
