### ISSUE TITLE
Form组件没有index，无法引入

### ISSUE THREAD

**Issue by mrzchen1** [ant-design/ant-design-mini#947]
## 组件

From
## 基础库版本

- [ ] 1.x
- [x] 2.x

## 手机系统

- [ ] iOS
- [x] Android
- [ ] HarmonyOS

## 组件库版本 

2.1.5
## 预期行为 

Form组件下没有index目录，无法引入组件
 "usingComponents": {
    "form": "antd-mini/es/Form/index"
  }
## 复现步骤 

1. 
2.

**Comment by DiamondYuan** [comment]
form 是在 js 里使用的， 在 axml 里没有 <form / > 这个组件

```
import { createForm } from 'antd-mini/es/Form/form';

Component({
  mixins: [createForm()],
  methods: {
    onChange(value) {
      this.emit('onChange', value);
    }
  }
})
```
