### ISSUE TITLE
Modal 组件样式不适配 iPad

### ISSUE THREAD

**Issue by CapQing** [ant-design/ant-design-mini#955]
## 组件

Modal
## 基础库版本

- [x] 1.x
- [ ] 2.x

## 设备机型
iPad Pro
## 手机系统

- [x] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

支付宝
## 组件库版本 

1.1
## 预期行为 

正常显示
## 复现步骤 

1. 使用Modal 组件（内嵌step）
2. 用 iPad 真机或模拟器打开

**Comment by DiamondYuan** [comment]
默认 modal 宽度为固定的 280px 
如果有特殊需求，可以通古 bodyStyle 修改宽度
