### ISSUE TITLE
期望在在popup完全打开后或完全关闭后触发回调

### ISSUE THREAD

**Issue by ChenHuiMing44** [ant-design/ant-design-mini#959]
## 背景
 
在popup完全打开后或者完全关闭后，可能需要有一定操作，例如触发某些方法、触发某些动画、完全打开后需要查看内部节点的rect之类
简单实用setTimeout不准确，看了下antd-mobile实现了该功能，期望antd-mini也实现下该功能；

## 期望
 
antd-mobile有实现类似功能，
![image](https://github.com/ant-design/ant-design-mini/assets/16046399/96a88d9b-d391-447c-8ff4-f1d30cdd63ff)
即在popup完全打开后或者完全关闭后触发回调

## 思路
 
看了下代码，antd-mini的打开关闭动画用的时
![image](https://github.com/ant-design/ant-design-mini/assets/16046399/39f8e88a-5420-465b-98a7-a7dc38af9299)
期望方法触发一个回调

**Comment by DiamondYuan** [comment]
已发布
