### ISSUE TITLE
带有Form组件的页面，在开发工具上第二次打开页面addItem报重名错误后奔溃；RangePicker组件一直警告onFormat事件

### ISSUE THREAD

**Issue by mustars** [ant-design/ant-design-mini#990]
## 组件

Form：在开发工具上第二次打开会造成奔溃。
RangePicker：一直提示找不到onFormat事件。

开发工具版本：3.8.4

## 基础库版本

- [x] 1.25.10
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## APP 

钉钉
## 组件库版本 

2.19.0
## 复现步骤 

1. A页面使用form组件
2. B页面打开A页面，第一次打开正常，第二次打开A页面报错【Form "addItem" same name: "fruit"】，后奔溃。
3. 在真机测试上正常
4. 另外RangePicker开发工具警告：【can not find event handle method: onFormat】

## 复现 demo

![image](https://github.com/ant-design/ant-design-mini/assets/26319610/55621e52-36ad-4686-b12e-96c7894cc339)

**Comment by DiamondYuan** [comment]
form 的问题可以看 https://github.com/ant-design/ant-design-mini/issues/812

**Comment by mustars** [comment]
handleRef(ref) {
    const props = ref.getProps() || ref.props
    if(this.form.fields[props.name])
      this.form.addItem(ref)
  },
  
使用上面的验证后虽然不报错了，但form定义的rules规则失效。

**Comment by mustars** [comment]
handleRef(ref) {
  const props = ref.getProps() || ref.props
  if(!this.form.fields[props.name])
    this.form.addItem(ref)
}
使用上面的验证后虽然不报错了，但form定义的rules规则在第二次进入后失效。

**Comment by DiamondYuan** [comment]
> addItem


页面加载的时候可以使用 form.updateRules 更新一下 rules 来临时解决。

具体原因我要再研究一下。

**Comment by mustars** [comment]
onLoad里面使用updateRules、setInitialValues等方法只生效一次，第二次进来也是没有效果。苹果真机测试没问题，不知其它机型；线上的版本也没问题，似乎只有在开发工具里异常。

**Comment by DiamondYuan** [comment]
```
 handleRef(ref) {
    this.form.addItem(ref);
  },
  onLoad() {
    this.form =  new Form();
  },
```

我试了一下这样是没问题的。
如果使用 demo 的写法， 每次 load 页面的时候， 组件重新初始化了，而 form 没有重新初始化。 这个时候就会有问题。
