### ISSUE TITLE
radio-group 中选项样式

### ISSUE THREAD

**Issue by CrossLee** [ant-design/ant-design-mini#998]
## 背景
目前用  <radio-group> 标签时，所有 radio 默认是挨着排列

## 期望
想要自定义样式，如：display: flex; justify-content: space-around

## 思路
<img width="332" alt="image" src="https://github.com/ant-design/ant-design-mini/assets/4584905/4bf897d3-000e-4486-a1e2-1aaf8ca8afdb">

**Comment by DiamondYuan** [comment]
可以在 page 里用 css 覆盖默认的 css
```
.ant-list-body .ant-radio-group-body {
  display: flex;
  justify-content: space-around;
}
```

![image](https://github.com/ant-design/ant-design-mini/assets/9692408/51c07483-5577-4038-81d8-e9b396e59586)


如果未生效，可以参考   [这里](https://ant-design-mini.antgroup.com/guide/faq#%E5%9C%A8%E6%94%AF%E4%BB%98%E5%AE%9D%E5%B0%8F%E7%A8%8B%E5%BA%8F-page-%E9%87%8C%E8%A6%86%E7%9B%96-antd-mini-%E7%9A%84%E6%A0%B7%E5%BC%8F%E4%B8%8D%E7%94%9F%E6%95%88)
